### ISSUE TITLE
Track 'Amobee'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#4359]
Vendor Site - https://www.amobee.com/
Example Site - https://www.crateandbarrel.com/
Category - 36 (Advertising)
Detection - Check for IMG tag with SRC as https://r.turn.com/r/beacon

**Comment by nurbek91** [comment]
Added to the ad category. But I did not find confirmation that https://r.turn.com/r/beacon refers to this technology. Perhaps you have some additional info information.

Also found many other examples that use apparently another product of this technology. 
![image](https://user-images.githubusercontent.com/3456008/140645437-00ebfb5c-a99c-44be-b882-1f78dc7c8fb4.png)
**privacy guidelines** - how to identify it correctly and in which category  can add it

**Comment by nurbek91** [comment]
Hey @AliasIO , might have to close
