### ISSUE TITLE
Track 'PayPal Credit' BNPL Solution

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#4500]
Vendor Site - https://www.paypal.com/uk/webapps/mpp/paypal-virtual-credit
Example Site - https://www.babymonitorsdirect.co.uk/ 
OR https://www.joules.com/Women/Clothing/Atherstone/Waterproof-Trench-Coat?size=10&id=214489|MARNAVY|10
OR https://direct.asda.com/george/women/shoes/beige-chunky-chelsea-boots/GEM839735,default,pd.html?cgid=D1M1G20C20

Category - Payment Processors (41) / Buy Now Pay Later (91)
Detection - Look for script '//www.paypalobjects.com/upstream/bizcomponents/js/versioned/smart-credit-message@1.26.5.js'

**Comment by rockeynebhwani** [comment]
Pay Later Example site - https://interview-guru.com/

**Comment by nurbek91** [comment]
.

**Comment by rockeynebhwani** [comment]
@nurbek91  - Are you able to pick this? PayPal is big player in BNPL space and without this, stats are incomplete for anybody looking at this category.

**Comment by rockeynebhwani** [comment]
@nurbek91 - This is still required

**Comment by nurbek91** [comment]
![image](https://user-images.githubusercontent.com/3456008/170707044-1b3f249a-61b8-4255-82b6-d54ca7dedf2d.png)
https://github.com/wappalyzer/wappalyzer/issues/4500#issuecomment-1037452934
Hey mate, decided to figure it out.
In general, the traces that you suggested have low latency
There is another option to check the link
There are about 11 thousand results
Can I use it to determine that the site uses bnpl from paypal?

**Comment by nurbek91** [comment]
https://www.halloweencostumes.com/dorothy-costume-long-dress.html
https://www.eurocarparts.com/
https://www.joules.com/Women/Clothing/Atherstone/Waterproof-Trench-Coat?size=10&id=214489|MARNAVY|10
https://www.babymonitorsdirect.co.uk/product/callowesse-apprise-baby-breathing-monitor-twin-pad-set/
https://global.direct.asda.com/george/women/coats-jackets/brown-quilted-longline-padded-coat/GEM863627,default,pd.html?cgid=D1M1G20C6&placement_id=item_page.pdpoos&strategy=bab_v2&config_id=item_page.pdpoos&parent_item_id=GEM839735&product_id=GEM863627&slotClicked=1

**Comment by rockeynebhwani** [comment]
@nurbek91 - This will work in most cases but sometimes may give you false positives... You can possibly avoid false positives by adding requiresCategory = ECommerce

Alternatively, you can check for JS object 'PaypalOffersObject'. Sites which clearly show paypal messaging on Product pages should have this JS object.
