### ISSUE TITLE
Technology is detected but icons are not shown.

### ISSUE THREAD

**Issue by baseplate-admin** [wappalyzer/wappalyzer#5470]
**Platform**
Which platform does the bug apply to?
* WebExtension (Mozilla Firefox)
* Website

**Describe the bug**
Summercart ( and PHP ) is being detected on https://drive.google.com/ but it's not shown.

**To Reproduce**
1. Go to 'https://drive.google.com/'
2. Click on 'extension icon'

**Expected behavior**
It should show summercart ( and PHP ). I donno if google uses summercart.

**Additional context**
- [CSV file](https://github.com/AliasIO/wappalyzer/files/7793803/wappalyzer_drive-google.com.csv)
- [Website Screenshot](https://user-images.githubusercontent.com/61817579/147771212-6cdbe121-847c-40f0-a833-d15726bece52.PNG )
- [Extension Screenshot](https://user-images.githubusercontent.com/61817579/147771249-9c821406-a045-4196-b9da-12e0ae216cae.PNG)

**Comment by AliasIO** [comment]
SummerCart should not be detected on Google Drive, I'll have a look at the fingerprint and fix up the icon. Thanks!

**Comment by baseplate-admin** [comment]
@AliasIO is there any update?

**Comment by AliasIO** [comment]
Is this still an issue?

**Comment by baseplate-admin** [comment]
Aha i see that it has been fixed. 

Sorry for the bad ping :)
