### ISSUE TITLE
Improve macaron detection

### ISSUE THREAD

**Issue by baseplate-admin** [wappalyzer/wappalyzer#5480]
**Platform**
Which platform does the bug apply to?
* WebExtension (Mozilla Firefox)
* Website

**Describe the bug**
Macaron should be detected. 

**To Reproduce**
1. Go to '[here](https://play.grafana.org/)'

**Expected behavior**
This extension should detect Macaron.

**Additional context**
- https://github.com/go-macaron/macaron#use-cases

**Comment by baseplate-admin** [comment]
This should be worked on after [this](https://github.com/AliasIO/wappalyzer/pull/5478) gets merged.

**Comment by baseplate-admin** [comment]
@nurbek91 Any ideas?

**Comment by nurbek91** [comment]
Hey @baseplate-admin, 
![image](https://user-images.githubusercontent.com/3456008/161805960-5d8b1ce2-8936-4096-bff4-469860e60388.png)
 It looks like it's already working.
