### ISSUE TITLE
Add Cloudflare pages

### ISSUE THREAD

**Issue by ajhawkings** [wappalyzer/wappalyzer#5483]
[Cloudflare pages](https://pages.cloudflare.com) is a JAMstack platform (static site hosting). It makes sense to add it to the PaaS category, along with GitHub pages and other competitors.

I didn't submit a pull request because I couldn't find anything that uniquely identified it, but I know these things about it:
- It always has `server: cloudflare` in the header, but that's common for any website with Cloudflare as the CDN
- In wappalyzer it usually shows Cloudflare Browser analytics in both analytics and RUM, and Cloudflare as CDN when cloudflare pages is used
- All Cloudflare pages sites are CNAMEs of a *.pages.dev subdomain if that helps with filtering

I hope someone smarter than me can find out how to filter for it :P

Examples of cloudflare pages: https://www.google.com/search?q=site%3A*.pages.dev plus many other sites that use a custom domain

**Comment by nurbek91** [comment]
Hey @ajhawkings , here, from the suitable fingerprints, I noticed only CNAME and probably it can give a  false positive results .
I have no other idea how to do this.

**Comment by ajhawkings** [comment]
This is still an issue
