### ISSUE TITLE
Migrating to manifest v3 for the Chrome extension

### ISSUE THREAD

**Issue by AbhinavS96** [wappalyzer/wappalyzer#5486]
**Is your feature request related to a problem? Please describe.**
Chrome is slowly [ending support](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/) for manifest v2 extensions. Of course, there is a long time before this would force us to upgrade but I thought it would be worth discussing. @nurbek91 @AliasIO

**Comment by AliasIO** [comment]
I'll be working on this soon-ish and aim to make the code compatible with both versions. Firefox support for Manifest v3 still isn't here.

**Comment by AliasIO** [comment]
MV3 support has been added in 6d3ba54fa9b71909dbc04e1f87998106184c222a.
