### ISSUE TITLE
XHR should match entire request URL not only hostname

### ISSUE THREAD

**Issue by Vasile-Peste** [wappalyzer/wappalyzer#5521]
XHR regex patterns should be tested on the entire XHR request URLs and not only on the hostnames.
Many services may refer to the same hostname when making XHR requests.

Why? Multiple products/widgets can make requests to the same domain. Testing only the hostname will make impossible to distinguish them.

For example I have some custom technologies definitions:
```json
"Facebook Audience Network": {
    "cats": [],
    "website": "https://developers.facebook.com/docs/audience-network/optimization/report-api",
    "xhr": "graph\\.facebook\\.com/.*/adnetworkanalytics/"
},
"Facebook lead ads": {
    "cats": [],
    "website": "https://developers.facebook.com/docs/marketing-api/guides/lead-ads/create",
    "xhr": "graph\\.facebook\\.com/.*/leadgen_forms"
},
```
basically any Facebook API Widget will request
`graph.facebook.com`, it's impossible to make difference between them since patterns are tested only on the hostname.
Instead if we check specific request endpoints, we can distinguish the technologies.

**Comment by Vasile-Peste** [comment]
This line should be responsible, https://github.com/AliasIO/wappalyzer/blob/8d21dbc1fc9845f5fa557a976a7b35cea6b709be/src/drivers/npm/driver.js#L534.

We should just replace `hostname` with `url`;

**Comment by AliasIO** [comment]
It only matches the hostname for performance. Some sites make multiple XHR requests per second, which would trigger Wappalyzer to run each time. Doing it only once per hostname is useful in most cases, but not all.

**Comment by Vasile-Peste** [comment]
Have you verified that there is a performance issue at all or you just suppose it's going to be a problem?
Another problem to avoid performance issue would be doing in this way
```
{
    "xhr": {
        "hostnameRegExpPattern": [ patternsToApplyOnCapturedHostnameRoutes ]
        "hostnameRegExpPattern2": [ patternsToApplyOnCapturedHostnameRoutes2 ]
        ...
    }
}
```

In this way we filter patterns by hostname and avoid testing them on all XHR requests.

**Comment by Vasile-Peste** [comment]
> It only matches the hostname for performance. Some sites make multiple XHR requests per second, which would trigger Wappalyzer to run each time. Doing it only once per hostname is useful in most cases, but not all.

By the way I'm using wappalyzer-core, so the problem you are describing is more related to your browser/data collection implementation rather than the core functionalities

**Comment by AliasIO** [comment]
> Have you verified that there is a performance issue at all or you just suppose it's going to be a problem?

Yes, it was an issue I had to solve early on. Initially it did match the full URL.

I will look into this more, there may be other optimisations that can be made.

**Comment by nurbek91** [comment]
.
