### ISSUE TITLE
CSP header

### ISSUE THREAD

**Issue by nurbek91** [wappalyzer/wappalyzer#5541]
**Is your feature request related to a problem? Please describe.**
Some technologies on some sites can only be detected through  CSP header
**Describe the solution you'd like**
Add for most popular enough technologies  CSP header verification 

We can update some up the technologies to use this header. Here's the CSP header for wappalyzer.com, where you can see things like Google Ads, GTM, Stripe, AWS, Vimeo, LinkedIn, reCAPTCHA and UptimeRobot. I'm actually no longer using LinkedIn but it's still in the CSP header. So using this header can result in incorrect detections sometimes but I think it's safe enough to use.

default-src 'self'; style-src 'self' 'unsafe-inline' *.gstatic.com *.crisp.chat; img-src 'self' data: *.linkedin.com *.google-analytics.com *.googletagmanager.com *.doubleclick.net *.crisp.chat *.google.com [...] *.google-analytics.com *.googletagmanager.com *.doubleclick.net *.stripe.com *.wappalyzer.com *.amazonaws.com *.uptimerobot.com wss://*.crisp.chat; worker-src 'none'; object-src 'none'; form-action 'self'; frame-ancestors 'none'; frame-src *.recaptcha.net *.stripe.com *.crisp.chat *.vimeo.com *.google.com; media-src 'self' *.crisp.chat; font-src 'self' *.crisp.chat
### 
Performer @nurbek91

**Comment by AliasIO** [comment]
You can use the `headers` field for that, something like:

```
"headers": {
  "content-security-policy": "\\.stripe\\.com"
}
```

**Comment by nurbek91** [comment]
Hey @AliasIO [This](#4413)  #4413 request may be closed.
Created a separate special thread to accumulate all requests related to this topic.

**Comment by nurbek91** [comment]
.
