### ISSUE TITLE
[Feature Package] NPM Package: Move to Playwright or allow configuration which to use

### ISSUE THREAD

**Issue by ThaDaVos** [wappalyzer/wappalyzer#5545]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is, e.g. I'm always frustrated when [...]

Currently I've got a NodeJs project using Playwright, so installing Puppeteer also seems really cumbersome

**Describe the solution you'd like**

An option to use Playwright instead of Puppeteer, or a version of the package which uses Playwright

**Describe alternatives you've considered**

Tried monkey patching in it, without succes

**Additional context**

**Comment by AliasIO** [comment]
I'm not familiar with Playwright. You can use an existing Puppeteer instance by setting the `CHROMIUM_WEBSOCKET` environment variable or `wappalyzer.browser` in JS. Does that help?

**Comment by AliasIO** [comment]
Ah, it's not Puppeteer based at all. It would require a completely new [driver](https://github.com/AliasIO/wappalyzer/tree/master/src/drivers) (interface between [Wappalyzer core](https://github.com/AliasIO/wappalyzer/blob/master/src/wappalyzer.js) and Playwright).

**Comment by ThaDaVos** [comment]
It's not puppeteer based, you can probably see it as a spiritual successor/rewrite, so it's mostly API compliant with Puppeteer.

Is it easy to write a new driver and hook it in?
Or would that require a rewrite of the package to support?

**Comment by AliasIO** [comment]
Everything in [driver.js](https://github.com/AliasIO/wappalyzer/blob/master/src/drivers/npm/driver.js) is Puppeteer specific, so that would have to be copied and adapted to the Playwright APIs. It's not hard but will likely require a fair amount of work. It could then be released as a separate NPM package.

You're welcome to create a fork for this but I don't think we'll maintain a Playwright driver officially.

**Comment by ThaDaVos** [comment]
The change isn't that hard as far as I can see - it only requires changing a few lines as the API's are mostly compliant with each other - but why does it require to be released as a seperate NPM package?

We could also choose to refactor the code so one can easily extend and re-use it, this would allow one to make more implementations when needed, ease support on the project and allow one to use different browsers and such. It would also allow one to implement a custom driver inside their project without having to copy the whole core - because now there's no real purpose to this package if one wants to change something, like use a different browser - as they would need to reïmplement the whole driver (wrapper around Wappalyzer-Core).

I think to do this, the project needs to be restructered and refactored in different modules/levels:

- Driver has to be split into modules/classes one only has to implement the specifics in, like how to open the browser, go to a page, evaluate a script on that page - this would make it a real Driver, instead of a wrapper around everything (as the Wappalyzer Core specifics don't need to be changed for each driver)
- Maybe rewrite in Typescript so it's easier to keep the types correct (One can also use JSDoc for this as light-weight solution)
- Rework an interface/adapter for Wappalyzer Core, instead of mangling it into the Browser driver

It's not that your package isn't great, I love it and it helps a lot - but for people building projects around, for example Playwright, also installing Puppeteer (with all it's legacy and installation issues) it may deter them from using it.

Maybe the Wappalyzer Core needs to be extracted to it's own repo, be made more integration ready (so if one needs to integrate with it, it's easier), for example by supplying classes or something one can import/extend on.

I would love to help you do this, I'll only have time in my spare time - but I think it can help everybody a lot to use this package.
Probably also makes it easier to integrate the package into other languages with wrapper scripts. like PHP/C# through inter-op

**Comment by AliasIO** [comment]
The setup is roughly how you describe it. Browser-specific code is in drivers and the common code is in wappalyzer-core. You can just install the very lightweight wappalyzer-core (18kB and no dependencies) and use it with any browser. A standard interface for drivers would be nice but it doesn't work in all cases. The WebExtension driver splits code between [driver.js](https://github.com/AliasIO/wappalyzer/blob/master/src/drivers/webextension/js/driver.js) and [content.js](https://github.com/AliasIO/wappalyzer/blob/master/src/drivers/webextension/js/content.js), while the NPM driver only has [driver.js](https://github.com/AliasIO/wappalyzer/blob/master/src/drivers/npm/driver.js). They're structured differently.

If the Puppeteer and Playwright APIs are mostly the same we could perhaps combine them but Puppeteer is listed as a dependency of the NPM package. A separate package would required to require Playwright instead.
