### ISSUE TITLE
Inconsistent results

### ISSUE THREAD

**Issue by ejerskov** [wappalyzer/wappalyzer#5577]
**Platform**
npm using wappalyzer package ^6.9.14

**Describe the bug**
When I run the test multiple times in a row I get different results.

**To Reproduce**
I run the wappalyzer scan (using this example code: https://github.com/AliasIO/wappalyzer/tree/master/src/drivers/npm) with the following options:

```
const options = {
  delay: 1000,
  maxDepth: 3,
  maxUrls: 10,
  maxWait: 10000,
  recursive: true,
  probe: true,
  noScripts: false
};
```

**Expected behavior**
I would expect to get the same result when I run in a few times in a row

**Comment by nurbek91** [comment]
Hey @ejerskov , as in request #5559 , 
there can be many reasons why the results differ.
If I'm not mistaken, the extension analyzes the current page. If you try to open several pages of the same site, you may notice that the number of technologies will gradually increase

npm, on the contrary, recursively looks at several pages at once. All this can be changed in the settings. Sometimes you can get 1-2 technologies like Cloudflare and the protection tool will not allow you to analyze the technologies on this site
