### ISSUE TITLE
Detecting custom element usage

### ISSUE THREAD

**Issue by justinfagnani** [wappalyzer/wappalyzer#5631]
**Is your feature request related to a problem? Please describe.**

It would be very informative to be able to detect custom element usage, regardless of the library used, or if no library is used, like with Wordle.

**Describe the solution you'd like**
There are probably two main ways to implement this:

1. Walk every element, including elements in shadow roots, and call `customElements.get()` with the tag name. If a constructor is returned, then custom elements are used.
2. If the extension can run early enough, before any custom elements are registered, patch `customElements.define()` and use any call to that as an indicator that custom elements are used.

**Describe alternatives you've considered**
There's no query selector that can detect custom elements.

**Additional context**

**Comment by AliasIO** [comment]
Thanks for the suggestion. It would be interesting but doesn't really fall within the scope of what Wappalyzer does.
