### ISSUE TITLE
Track 'towerdata'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#5715]
Vendor site - http://intelligence.towerdata.com/ (It was known as 'Rapleaf' before)
Example site - https://rothys.com/products/the-lightweight-tote-coffee-brown
Category - Fraud
Detection - track for <img> tag with source from domain  'https://idsync.rlcdn.com'

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , here I doubt the category. But I don't have more information. Can u confirm that the category is correct.  At first glance, it looks like the email category.

**Comment by rockeynebhwani** [comment]
@nurbek91  - I didn't realise we had 'Email' category. Towerdata also uses email data for fraud prevention hence I thought 'Fraud' can be appropriate category here.

**Comment by nurbek91** [comment]
still required

**Comment by rockeynebhwani** [comment]
.

**Comment by dhavalveera** [comment]
@rockeynebhwani - can you please share the more example of where `towerdata` is being implemented? as your given Example Site isn't working
