### ISSUE TITLE
Track 'threekit'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#5725]
Vendor site - https://www.threekit.com/
Example site - https://www.crateandbarrel.com/curve-marble-and-glass-hurricane-candle-holder-12.5/s391507
Category - ?? (May be use 'Miscellaneous) 
Detection - Look for JS object 'threekitAR' and script 'threekit.js'

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , 
![image](https://user-images.githubusercontent.com/3456008/158506370-b0b89969-4ac2-4e07-bbba-c204bb7af27d.png)
I found a similar previously added technology. We have it in the personalisation category.
What do you think?

**Comment by rockeynebhwani** [comment]
@nurbek91  - Yes... we can categorise this in 'personalisation' as they also offer some tools for personalisation/product configuration..

@AliasIO / @nurbek91  - May be at some point it also makes sense to introduce a new category for 'AR' and include solutions like this. We also currently detect 'WebAR' as a technology but it sits under 'Miscellaneous'

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , added to personalisation and digital asset management category, thanks!!!
I will later explore the number of technologies that can fall into the new category.
If there are more than 10-15 of them, in principle, we can probably make a separate list of all of them
