### ISSUE TITLE
Track 'Stage Try'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#5784]
Vendor site - https://stagetry.com/
Category - Buy now pay later (This is not exactly a BNPL solution but I don't think we have an exact category for such solutions so I am recommending that we categorise this under BNPL for now). 
Example Site - https://globaltrendz.ca/collections/bubble-cotton-scarves/products/magenta-bubble-cotton-scarf
Detection - Look for DIV with class 'stageTryNowButton'
                  - Look for script '//elements.stagemarketplace.io/js/stage-try.js'

**Comment by nurbek91** [comment]
Hey @rockeynebhwani, few results, doesn't fit into any category, maybe we'll skip it.
