### ISSUE TITLE
Improve 'GTranslate' detection

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#5793]
Site where it's not working - https://bymilaner.com/collections/clutches/products/the-meg-woven-clutch?variant=39488094175290

Current detection (looks like we only have wordpresss specific detection)- 

```
  "GTranslate": {
    "cats": [
      87,
      89
    ],
    "description": "GTranslate is a website translator which can translate any website to any language automatically.",
    "dom": "link[href*='/wp-content/plugins/gtranslate/'], img[src*='/wp-content/plugins/gtranslate/']",
    "icon": "GTranslate.svg",
    "pricing": [
      "freemium",
      "low",
      "recurring"
    ],
    "requires": "WordPress",
    "website": "https://gtranslate.io"
  },
```

Improve this buy looking for JS object 'gtranslate_installed' and by looking for script '//gtranslate.io/shopify/gtranslate.js'

**Comment by nurbek91** [comment]
Hey @rockeynebhwani 
Added as an application for Shopify.
Later, we can add just as GTranslate and rename the current GTranslate to GTranslate plugin
And for the GTranslate plugin and the GTranslate app, we will need to remove the translation category and add the line **implies**. 
Then we will win in performance and get the total number
