### ISSUE TITLE
Track 'Glider'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#5808]
Vendor site - https://glidejs.com/
Category - Javascript Libraries
Example Site - https://www.honeybum.com/products/midnight-kiss-dress-black
Detection - Look for script '//cdn.jsdelivr.net/npm/glider-js@1/glider.min.js'

**Comment by nurbek91** [comment]
Hey @rockeynebhwani ,
Here i need to add
https://glidejs.com/
or
https://nickpiscitelli.github.io/Glider.js

**Comment by nurbek91** [comment]
gilder more popular than glide

**Comment by rockeynebhwani** [comment]
Still needed
