### ISSUE TITLE
Proposal for a new category for 'Cross Border Commerce'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#5824]
We currently list all 'Cross Border Commerce' solution providers under 'Ecommerce' whereas purpose of Ecommerce category should be providers of Core Commerce platforms.. (though we sometime add other stuff due to not having granular categories). I think it will be good if we can create a new category for 'Cross Border Commerce' category and move following tech from 'Ecommerce' to 'Cross Border Commerce' category. 

- Global-e
- Flow
- Borderfree
- Zonos
- Localised
- WorldShopping
- Exemptify (https://github.com/AliasIO/wappalyzer/issues/5805)
- Global Shopex (https://github.com/AliasIO/wappalyzer/issues/5820)
- Reach (https://github.com/AliasIO/wappalyzer/issues/5817)

**Comment by rockeynebhwani** [comment]
@nurbek91  / @AliasIO  - Are you OK with this proposal? I am doing some where this will be helpful.. I am happy to pick this if you are happy with proposal..

**Comment by rockeynebhwani** [comment]
@AliasIO  - Are you happy to proceed with this?

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , yesterday received a positive confirmation for Livestreaming and Ticket booking category.

**Comment by nurbek91** [comment]
Since it is strange that some websites show several e-commerce platforms at once. Even @AliasIO  told me that there should always be 1 technology for 1 site in the e-commerce categories

**Comment by AliasIO** [comment]
Would this just be for technologies that facilitate international sales but are not ecommerce platforms? I suppose technically any ecommerce platform can be cross border.

**Comment by rockeynebhwani** [comment]
@AliasIO - Yes... technically any ecommerce platform can be cross border but there is a set of solutions in market which makes it easier for retailers to do cross-border commerce. These solutions are integrated on top of base eCommerce platform. Intention is to list all such solutions under this category otherwise core 'Ecommerce' category gets polluted and not true reflection of Ecommerce platforms... 

Some examples are listed in this particular issue. Cross Border Commerce solutions alone can't deliver the whole experience. They are always integrated on top of a base commerce platform.

**Comment by AliasIO** [comment]
@nurbek91 Happy to add this one. It should only be used for technologies that don't fit in the Ecommerce category.
