### ISSUE TITLE
Track 'AnswerDash'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#5826]
Vendor site - https://www.answerdash.com/
Category - ??
Example Site - https://spiceology.com/products/marley-kitchen-one-love-seasoning-glass-jar/
Detection - Look for JS object 'AnswerDash'
                  - Look for script from domain '//p1.answerdash.com'

**Comment by nurbek91** [comment]
Hey , added to widget cat , Looks like a widget with frequently asked questions on websites
