### ISSUE TITLE
Track 'Chord'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#5827]
Vendor site - https://m.chord.us/
Category - ??
Example Site - https://spiceology.com/products/marley-kitchen-one-love-seasoning-glass-jar/
Detection - Look for JS object 'ChordConnect'
- Look for script from domain '//vcadmin.chord.us/'

**Comment by nurbek91** [comment]
https://trends.builtwith.com/widgets/Chord-Connect
https://publicwww.com/websites/%22vcadmin.chord.us%2F%22/
Few results. Should this technology be added?
