### ISSUE TITLE
Track 'Parrable'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#5828]
Vendor site - https://parrable.com/
Category - Analytics
Example Site - https://spiceology.com/products/marley-kitchen-one-love-seasoning-glass-jar/
Detection - Look for JS object 'parrableId'
                 - Look for scripts from domain '//h.parrable.com/'

**Comment by nurbek91** [comment]
Very few results
Is technology needed anyway?
