### ISSUE TITLE
Track 'Bold Product Options'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#5833]
Vendor site - https://apps.shopify.com/product-options
Category - Shopify Apps
Example Site - https://keeb.io/collections/iris-split-ergonomic-keyboard/products/iris-rev-5-keyboard-pcbs-for-split-ergonomic-keyboard
Detection - Look for script '//option.boldapps.net/js/options.js'

**Comment by nurbek91** [comment]
Hey @rockeynebhwani  added : 
Bold Commerce,
Bold Brain,
Bold Bundles,
Bold Custom Pricing,
Bold Motivator,
Bold Product Options,
Bold Subscriptions,
Bold Upsell.
