### ISSUE TITLE
Track 'Coin Currency Converter' by ShopPad

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#5855]
Vendor site - https://apps.shopify.com/coin
Category - Shopify Apps / Cross Border Commerce (Also see - https://github.com/AliasIO/wappalyzer/issues/5824)
Example Site - https://en.stop-vieillissement.com/
Detection - Look for scripts with path '/apps/coin/coin.js'

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , I left only one category.
I don't think it fits the new category. But ready to add if you insist on it
