### ISSUE TITLE
Track 'Plaza'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#5862]
Vendor site - https://www.useplaza.com/
Category - ?? I think we should introduce a new category called 'Livestreaming' as it's growing trend and more and more products are appearing in this category. 
Example Site - https://www.pothosbeauty.com/pages/livestream
Detection - Look for an IFRAME with SRC from domain '//stream.useplaza.com/'

**Comment by rockeynebhwani** [comment]
@nurbek91  - Some other candidates for this new proposed category - 

Bambuser - https://www.wappalyzer.com/technologies/miscellaneous/bambuser/
Hero - https://www.wappalyzer.com/technologies/ecommerce/hero/

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , thanks!!!
yes looks like god if similar technologies in different categories, but without @AliasIO  approval, I can't add categories. Let's wait for his answer

**Comment by AliasIO** [comment]
Let's do it 👍
