### ISSUE TITLE
Track 'Transunion'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#5874]
Vendor site - https://www.transunion.com/
Category - Security
Example Site - https://rothys.com/
Detection - Look for requests to domain 'aa.agkn.com'

I don't see this request on desktop from UK but you should see it from US on mobile as seen in this webpagetest waterfall - https://www.webpagetest.org/video/compare.php?tests=220316_AiDcQX_K8V-r:1-c:0. If you don't see the request on example site, try accessing from US (on mobile)

agkn.com domain was for 'Aggregate Knowlege' which got acquired by 'Neustar' (https://www.crunchbase.com/organization/aggregateknowledge) and 'Neustar' got acquired by 'Transunion'

**Comment by nurbek91** [comment]
Hey @rockeynebhwani ,
examples:
https://publicwww.com/websites/%22agkn.com%22/
We also have this technology. What do you advise to do?
```
"TruValidate": {
    "cats": [
      16,
      83
    ],
    "description": "TransUnion TruValidate (previously ReputationShield/IDVision from iovation) is an online risk and fraud detection platform.",
    "icon": "TruValidate.svg",
    "pricing": [
      "poa"
    ],
    "saas": true,
    "scriptSrc": [
      "mpsnare\\.iesnare\\.com",
      "ci-mpsnare\\.iovation\\.com"
    ],
    "website": "https://www.transunion.com/solution/truvalidate"
  },
```
