### ISSUE TITLE
Improve 'Growave' detections

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#5877]
@nurbek91  - I see that you had added 'Growave' as part of https://github.com/AliasIO/wappalyzer/pull/5218. I think we can improve this further as we have more granular categories and in case of 'Growave' we can detect usage of exact product they offer... 

Name - Growave Social Login
Vendor - https://growave.io/app/social-login
Category - Authentication
Example - https://www.iheartraves.com/collections/face-masks/products/trip-buddies-face-mask-newtype?color=Blue/Purple
Detection - Look for script '//static.socialshopwave.com/ssw-assets/login-*'

Name - Growave Loyalty & Rewards
Vendor - https://growave.io/app/loyalty-rewards
Category - Loyalty & Rewards 
Example - https://kamiidea.com/
Detection - Look for script with pattern - '//static.socialshopwave.com/ssw-assets/reward-*'

Name - Growave Reviews
Vendor - https://growave.io/app/social-reviews
Category - Reviews
Example - https://www.almadelunamoda.com/en
Detection - Look for script with pattern - '//static.socialshopwave.com/ssw-assets/review-*'

Name - Growave Curation
Vendor - https://growave.io/app/instagram-photos
Category - Content Curation
Example - ??
Detection - Look for script with pattern -  (Trying to find example)

**Comment by nurbek91** [comment]
Hey @rockeynebhwani 
![image](https://user-images.githubusercontent.com/3456008/159754262-c35e7a59-5f62-4554-b5a2-fbe32fdf7d74.png)
Should they be separated? Because they all go together.

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , Need your further instructions here.

**Comment by nurbek91** [comment]
.
