### ISSUE TITLE
Improve 'AfterPay' detection

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#5883]
@nurbek91 - I am not seeing 'AfterPay' in chrome extension on this page even though it has JS object 'Afterpay' - https://www.reef.com/collections/men/products/mens-sandals-reef-draftsmen-bronze-brown?variant=41837320667291

- Can we please also look for script from domain '//js.afterpay.com'?
- Also get version from Afterpay.version

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , I don't see any traces on this link.

**Comment by rockeynebhwani** [comment]
@nurbek91  -Sorry.. may be I copy pasted wrong URL when I had multiple tabs open... Try this - https://www.dillards.com/search-term/floral/women 

This has script from domain 'js.afterpay.com' .. though on this site, detection seems to work anyways.. I can't remember what the site was when I noticed this issue

**Comment by nurbek91** [comment]
![image](https://user-images.githubusercontent.com/3456008/162242430-8d6a67d9-55b1-4cc9-a303-2015f39c3bab.png)
Hey mate,  I also thought at the beginning that there is a bug for the Chrome extension. But after several page updates, the technology was determined
