### ISSUE TITLE
Track 'Vntana'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#5889]
Vendor site - https://www.vntana.com/
Category - Augmented Reality (@nurbek91  - we discussed about this category)
Example Site - ?? (Trying to find one)
Detection - Look for iFRAME with SRC from domain 'embed.vntana.com' (Got this from video on this link - https://apps.shopify.com/vntana-platform .. See clip at 00:08 Sec)

**Comment by nurbek91** [comment]
5725

**Comment by nurbek91** [comment]
Didn't find any example
Like in the future it should appear.

![image](https://user-images.githubusercontent.com/3456008/161845993-fa793576-89cc-44a3-96cb-d38a5848fea8.png)
![image](https://user-images.githubusercontent.com/3456008/161846018-245eaec5-fb99-47d9-af22-aa3b16f2033f.png)
If you need to add in advance, tell me and I will probably add
