### ISSUE TITLE
Improve 'Magento' detection

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#5895]
It's not working on this site - https://www.avenue.com/

this page has cookies like 'mage-cache-storage-section-invalidation' and 'mage-cache-storage'. These are cookies specific to 'Magento' platform - https://docs.magento.com/user-guide/stores/cookie-reference.html

Also, while fixing this, it will make sense to rename this to 'Adobe Commerce' and update the website URL to - https://business.adobe.com/products/magento/magento-commerce.html

**Comment by nurbek91** [comment]
Looks like it's working now
![image](https://user-images.githubusercontent.com/3456008/161438527-13a86fdf-a525-41c1-9aa8-4c1b3ffce050.png)

**Comment by nurbek91** [comment]
Hey @rockeynebhwani, Can we call all Magento sites Adobe Commerce.
Maybe we should split Magento and Magento Commerce(Adobe Commerce)
Although I'm not sure yet if it can be done. I need to study the issue

**Comment by nurbek91** [comment]
.
