### ISSUE TITLE
Proposal to rename 'Shipping Carriers' category to 'Fulfilment' 

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#5916]
@AliasIO  / @nurbek91  - Currently we have some Fulfilment/Carriers related solutions which are in various categories. These solutions will be best placed alongside 'Shipping Carriers' OR a new category.. If we end up choosing 'Shipping Carriers' category for this purpose, it will be good to rename it as 'Fulfilment'. We recently added a new category for 'Returns' so 'Fulfilment' as a broad category makes sense alongside 'Returns' .. What do you think?

Some Examples - 
- Shoprunner (https://www.wappalyzer.com/technologies/ecommerce/shoprunner/) --> Currently under 'Ecommerce' category. It's not really an Ecommerce platform. This will be a good candidate.
- Route (https://www.wappalyzer.com/technologies/miscellaneous/route/) --> Currently under 'Miscellaneous' category. 

I have seen more solutions which will be good candidate for 'Fulfilment' category.. I will add those to this issue when I remember those...

**Comment by rockeynebhwani** [comment]
@AliasIO  - thoughts on this?

**Comment by AliasIO** [comment]
Happy to add a Fulfilment category but I think we'd keep the Shipping Carriers separate as it's just for postal services and couriers.

**Comment by rockeynebhwani** [comment]
Sure @AliasIO .. That works..

**Comment by AliasIO** [comment]
@nurbek 🙏

**Comment by rockeynebhwani** [comment]
@nurbek91  This is still needed
