### ISSUE TITLE
Track 'Vonage Video API'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#5927]
Vendor site - https://www.vonage.com/communications-apis/video/ (Also see - https://tokbox.com/developer/sdks/js/)
Category - Livestreaming
Example Site - https://www.thelight-salon.com/pages/virtual-light-salon 
Detection - Look for script from domain '//static.opentok.com/'

**Comment by nurbek91** [comment]
#5862
