### ISSUE TITLE
Track 'Poloriz'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#5951]
Vendor site - https://apps.shopify.com/poloriz
Category - Shopify Apps
Example Site - https://blackbeardbrigade.com/collections/all
Detection - Look for script from domain '//widget.poloriz.com/'

**Comment by nurbek91** [comment]
Hey @rockeynebhwani ,
the identifier is found not only on Shopify sites.
That's why I chose the personalisation category. I hope I got the category right.

**Comment by rockeynebhwani** [comment]
@nurbek91 - Sure.. I didn't realise that it was outside Shopify based sites also... How do you do this check? Do you have scrapped HTMLs somewhere to do a quick search ?

**Comment by rockeynebhwani** [comment]
@nurbek91  - and yes personalisation will be correct category in that case.

**Comment by nurbek91** [comment]
@rockeynebhwani  I use this website : https://publicwww.com/websites/%22.orderlogicapp.com%2F%22/

**Comment by nurbek91** [comment]
But the situation is strange, some WordPress sites have commented out this piece of code.
As if the startup changed its direction and the link remained old.
But the official site lists different ecommerce platforms

**Comment by rockeynebhwani** [comment]
> @rockeynebhwani I use this website : https://publicwww.com/websites/%22.orderlogicapp.com%2F%22/

Thanks.. this is cool

**Comment by nurbek91** [comment]
> > @rockeynebhwani I use this website : https://publicwww.com/websites/%22.orderlogicapp.com%2F%22/
> 
> Thanks.. this is cool

Yes, very helpful site. Save a lot of time and help avoid mistakes.
Using your keywords, I play there by asking different queries.
We can quickly understand whether javascript files are connected in different ways, shopify cdn, or there are other types.
Should I make it more granular if this company has a lot of results for its other applications
