### ISSUE TITLE
Track 'Darkly'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#5952]
Vendor site - https://apps.shopify.com/darkly-dark-mode-for-stores
Category - Shopify Apps
Example Site - https://darkly-demo-store.myshopify.com/collections/all
Detection - Look for DIV with class 'darkly-switch-container'

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , low frequency of results,  maybe we can leave it for the future.
