### ISSUE TITLE
Track 'Ordergroove'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#5956]
Vendor site - https://www.ordergroove.com/
Category - Subscriptions (There is no such category but I think we should have a category for subscriptions.. this can contain solutions like 'Recharge' and many others)
Example Site - https://www.missouriquiltco.com/products/creative-grids-cutting-mat-24-x-36
Detection - Look for script from domain '//static.ordergroove.com/'

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , here we have previously added similar technologies to the  Payment proc category 
some of them: 

`"Recurly": {
    "cats": [
      41
    ],
    "description": "Recurly provides enterprise-class subscription billing and recurring payment management for thousands of businesses worldwide.",
    "html": "<input[^>]+data-recurly",
    "icon": "Recurly.png",
    "js": {
      "recurly.version": "^(.+)$\\;version:\\1"
    },
    "scriptSrc": "js\\.recurly\\.com",
    "website": "https://recurly.com"
  },`


`"Chargebee": {
    "cats": [
      41
    ],
    "description": "Chargebee is a PCI Level 1 certified recurring billing platform for SaaS and subscription-based businesses.",
    "icon": "Chargebee.svg",
    "js": {
      "Chargebee": "",
      "chargebeeTrackFunc": ""
    },
    "pricing": [
      "mid",
      "recurring"
    ],
    "saas": true,
    "scriptSrc": "js\\.chargebee\\.com/v([\\d.]+)\\;version:\\1",
    "website": "https://www.chargebee.com"
  },`

Seal Subscriptions and Skio -  these are shopify apps as you mentioned. I'm not sure how to separate them correctly.

```
"Chargebee": {
    "cats": [
      41,
     Subscriptions_ID
    ],
```

```
"Skio": {
    "cats": [
      100,
     Subscriptions_ID
    ],
```
It's possible to do it this way if @AliasIO will approve the addition of a new category

**Comment by nurbek91** [comment]
2Checkout (now Verifone)
SageIntacct
Profitwell
Go Cardless
SaaS Optics
Zuora
Stripe
Recurly
Chargify
Chargebee 
top 10 to see for me

**Comment by rockeynebhwani** [comment]
.

**Comment by nurbek91** [comment]
Still needed after the merge
