### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by eduardoportilho** [wappalyzer/wappalyzer#5982]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome)
* Website

**Describe the bug**
I have found several entries on our react application's logs with the following stack trace:
```
TypeError: Cannot convert undefined or null to object
  at Function.keys(<anonymous>)
  at ? (chrome-extension://gppongmhjkpfnbhagpmjfkannfbllamg/js/dom.js:20:20)
  at Array.reduce(<anonymous>)
  at onMessage(chrome-extension://gppongmhjkpfnbhagpmjfkannfbllamg/js/dom.js:19:29)
  at apply(webpack://.../node_modules/@sentry/browser/esm/helpers.js:88:17)
  at wrapped(webpack://.../node_modules/logrocket/dist/build.umd.js:1072:33)
```
Searching for the Chrome extension ID that appears in the logs I found that it is [Wappalyzer](https://chrome.google.com/webstore/detail/wappalyzer/gppongmhjkpfnbhagpmjfkannfbllamg). Could you provide any tips to help me understand why the extension is causing these errors on our app?

**Comment by eduardoportilho** [comment]
It looks like that [in this line](https://github.com/wappalyzer/wappalyzer/blob/15bc91b9189be614d5475a8cb48766046f2c3c79/src/drivers/webextension/js/dom.js#L20) the value of `dom` can be undefined or null.

**Comment by AliasIO** [comment]
Thanks. This shouldn't really happen in the first place but added a try/catch to suppress the error when it does in f977f42bf87c9801079018ec196a357da54c709d. It's not causing an error in your app but the script is inject into the page, which is why the error shows up in your logs.
