### ISSUE TITLE
Track 'PERFECT' / 'YouCam Makeup'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#5986]
Vendor site - https://makeupar.com/
Category - Augmented Reality (See discussion here - https://github.com/wappalyzer/wappalyzer/issues/5725#issuecomment-1070818810)
Example Site - https://fentybeauty.com/products/gloss-bomb-universal-lip-luminizer-cheeky 
                       - https://www.maccosmetics.co.uk/product/13840/363/products/makeup/eyes/eyeshadow/eyeshadow?shade=Memories_of_Space
Detection - Look for scripts from domain '//plugins-media.makeupar.com/' OR '//plugins-media.perfectcorp.com/'

Not sure of the exact name.. Got 'YouCam' brand from their website footer and when you use the feature on retail sites, it's branded as 'YouCam Makeup'

**Comment by nurbek91** [comment]
Hey added, YouCam Makeup seems to be better 
https://www.perfectcorp.com/business/services/youcam-4-web
https://www.perfectcorp.com/business/showcase/youcam-tutorial
