### ISSUE TITLE
Track 'Boomupsell'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#5988]
Vendor site - https://boomupsell.com/
Category - Shopify Apps
Example Site - https://flightplatestamps.com/products/custom-rubber-stamp
Detection - Look for scripts from domain '//boomupsell.com/'

**Comment by nurbek91** [comment]
and examples without traces now

**Comment by rockeynebhwani** [comment]
Thanks @nurbek91 .. Closing it.
