### ISSUE TITLE
Increase coverage of apps under 'Shopify Apps' category

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#6004]
@nurbek91  - Please see this - https://github.com/feracommerce/shopify_app_detector/blob/master/data/shopify_apps.js

You can go through this and try to incorporate this in Wappalyzer

**Comment by nurbek91** [comment]
Hey,thank you. Once I've dealt with all the rest of your requests, I'll start to study this list.

**Comment by nurbek91** [comment]
still required

**Comment by nurbek91** [comment]
.

**Comment by rockeynebhwani** [comment]
.

**Comment by nurbek91** [comment]
Hey mate, yes i will take a look

**Comment by nurbek91** [comment]
Hey mate , @rockeynebhwani 
added a few applications, I will continue to add further. 
need help and I have a question for you. Do you know how you can tell Shopify from Shopify Plus?

**Comment by AliasIO** [comment]
No, there's no way to differentiate Shopify and Shopify Plus.

**Comment by nurbek91** [comment]
> No, there's no way to differentiate Shopify and Shopify Plus.

Ah ok, thanks mate!!
