### ISSUE TITLE
Track 'Fitmix'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#6010]
Vendor site - https://www.ocuco.com/fitmix/
Category - Augmented Reality (Also see https://github.com/wappalyzer/wappalyzer/issues/5889 and https://github.com/wappalyzer/wappalyzer/issues/5986)
Example Site - https://www.fashioneyewear.co.uk/versace-ve2054.html
Detection - Look for script 'fitmix.js' AND JS object 'FitMix'

**Comment by nurbek91** [comment]
#5725
