### ISSUE TITLE
Track 'Luna'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#6011]
Vendor site - https://luna.io/
Category - Augmented Reality 
Example Site - https://www.eyeconic.com/on/demandware.store/Sites-eyeconic-Site/default/DittoPage-Show?pid=454736410741_MARCHON&sku=454736410741&pageId=pdp
Detection - Look for JS object 'dittoCreation' AND Script from domain '//bsdk.api.ditto.com/'

FYI - Ditto, 6over6, Premium Vision and ExpressExam have joined forces and are now Luna.  Also see - https://luna.io/newsroom/1-800-contacts-announces-acquisition/

**Comment by nurbek91** [comment]
#5725
