### ISSUE TITLE
Track 'Modiface'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#6012]
Vendor site - https://modiface.com/
Category - Augmented Reality
Example Sites - 
- https://www.yslbeauty.co.uk/makeup/lips/lipsticks/rouge-pur-couture-the-slim-lipstick/WW-50192YSL.html?pdp=storeview
- https://www.garnier.co.uk/virtual-try-on
Detection - Look for JS object 'initModiface' AND iframe with id 'mf_ppa_frame'

**Comment by nurbek91** [comment]
#5725
