### ISSUE TITLE
WebExtension doesn't show some tech

### ISSUE THREAD

**Issue by John4266** [wappalyzer/wappalyzer#6032]
Take a look at the following website: https://sucuri.net/
It seems to be using the following Live Chat technology: `Olark`
When using the latest release version of the Wappalyzer extension on both browsers (Chrome/Firefox), it appears to miss it.

Firefox:
![](https://i.imgur.com/2F7RCN7.png)

Chrome:
![](https://i.imgur.com/bXCGO8g.png)

However, the website itself does detect it:
https://www.wappalyzer.com/lookup/sucuri.net
![](https://i.imgur.com/tOE11jW.png)

p.s.: sorry for not using the bug report format, it was complicated to use it for this case.

**Comment by nurbek91** [comment]
Hey @John4266 , thanks!! 
It's very strange that scriptScr doesn't work. Even though everything is correct.
Added JS attribute. began to determine at least locally.
