### ISSUE TITLE
Track 'Richpanel'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#6033]
Vendor site - https://richpanel.com/
Category - Live Chat ? (But they are much more than Live Chat)
Example Site - https://www.shethinx.com/pages/thinx-reviews
Detection - Look for scripts from domain '//cdn.richpanel.com/' AND JS object 'richpanel'

**Comment by nurbek91** [comment]
_**Category - Live Chat ? (But they are much more than Live Chat)**_

Hey mate, Added as CRM
Some examples show live chat systems of other services.
