### ISSUE TITLE
Track 'ReturnMagic'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#6040]
Vendor site - http://returnmagic.com/
Category - Returns
Example Site - https://kanalifestyle.com/a/returns
Detection - Look for IFRAME with SRC '//services.alveo.io/'

**Comment by nurbek91** [comment]
https://support.returnmagic.com/hc/en-us/articles/4417517429403-Return-Magic-is-closing-down-on-July-6th-2022-Here-s-what-you-need-to-do
