### ISSUE TITLE
Update 'Oribi'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#6042]
Oribi was acquired by LinkedIn. I think it will make sense to update this with. - https://www.wappalyzer.com/technologies/analytics/linkedin-insight-tag/

see announcement here - https://www.linkedin.com/business/marketing/blog/linkedin-ads/helping-customers-build-smarter-campaigns-with-a-new-investment-in-marketing-attribution-technology?_l=en_US

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , should I merge them or add for Oribi implies attribute

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , Need your further instructions here.

**Comment by rockeynebhwani** [comment]
@nurbek91  - I suggest merge them
