### ISSUE TITLE
Track 'Upsellprogressbar'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#6046]
Vendor site - https://apps.shopify.com/upsellprogressbar
Category - Shopify Apps
Example Site - https://www.helle-kleven.shop/
Detection - Look for script from domain '//upsell-progress-bar.web.app'

**Comment by nurbek91** [comment]
![image](https://user-images.githubusercontent.com/3456008/177051551-6728b18a-a7f1-42db-b309-9659d2fb6f18.png)
![image](https://user-images.githubusercontent.com/3456008/177051555-8c68b75e-050b-4b95-8649-6fc7b00a3f72.png)
Can we skip this technology?

**Comment by rockeynebhwani** [comment]
@nurbek91  - ok. Let's skip this
