### ISSUE TITLE
Track 'DropInBlog'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#6047]
Vendor site - https://dropinblog.com/
Category - ??
Example Site - https://www.helle-kleven.shop/
Detection - Look for script from domain '//dropinblog.com/'

**Comment by nurbek91** [comment]
The same technologies were previously added to the Blog category
https://www.quora.com/What-is-a-free-alternative-to-DropInBlog-to-embed-a-blog-into-your-existing-site
