### ISSUE TITLE
Improve 'Shopify' detection

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#6061]
Following shopify sites where detection is not working because these sites are using headless architecture. You may see it being detected as you progress through the checkout flow - 

- https://iliabeauty.com/ (Check Detection 1)
- https://kotn.com/
- https://www.seedlipdrinks.com/ (Check Detection 2)
- https://nakedlabs.com/ (Check Detection 3)
- https://ensorings.com/ (Check Detection 1)
- https://www.analuisa.com/
- https://www.onequince.com/
- https://www.tamaramellon.com/products/astral-suede-sandals?color=Teal%20Yade&origin=hp-carousel

Will add more examples and provide some directions on how we can improve this

Detection - 

1) Look for '?shop=*.myshopify.com' within SCRIPT SRC URL. This is typically included by loading Shopify APP JS and this can be a useful signal 
2) Refer https://github.com/wappalyzer/wappalyzer/issues/6048. We can 'Imply' Shopify when 'Shopify Buy' button is found
3) Look for URLs from domain '//cdn.shopify.com/' in `<video>` tag 'poster' attribute  (may be give this confidence level of 50%)
4) Also see https://github.com/wappalyzer/wappalyzer/issues/6223

**Comment by nurbek91** [comment]
.

**Comment by nurbek91** [comment]
still required

**Comment by nurbek91** [comment]
https://porijewelry.faire.com/product/p_f9827vvus7

**Comment by rockeynebhwani** [comment]
.
