### ISSUE TITLE
Track 'Rely' BNPL

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#6083]
Vendor site - https://www.rely.sg/
Category - Buy now pay later / Payment processors
Example Site - https://missfit.com.sg/collections/marimekko-collection/products/adidas-x-marimekko-training-tank-tee-hc6853-white
Detection - Look for script 'rely-shopify.min.js'

**Comment by rockeynebhwani** [comment]
Still needed

**Comment by nurbek91** [comment]
![image](https://user-images.githubusercontent.com/3456008/180084300-e6190af6-1298-484e-9735-14aa8cd31645.png)
![image](https://user-images.githubusercontent.com/3456008/180084333-59f936c6-877a-42f6-a16b-b78cb86a5808.png)

**Comment by nurbek91** [comment]
I see JS traces but I don't see on the front of the offer site. Is it by any chance shopify app?
![image](https://user-images.githubusercontent.com/3456008/180085909-cce3125d-0c8b-45a9-980a-b0ade9d92418.png)
![image](https://user-images.githubusercontent.com/3456008/180085936-f71b7bf4-d729-43b6-8758-482b7dea73bc.png)

**Comment by nurbek91** [comment]
https://missfit.com.sg/collections/marimekko-collection/products/adidas-x-marimekko-training-tank-tee-hc6853-white
https://www.picketandrail.com/products/kuka-2537-fabric-sofa-2-seater-color-c-1075?variant=16921021972550

**Comment by rockeynebhwani** [comment]
@nurbek91 - looks like Rely is now part of Pace - https://www.pymnts.com/acquisitions/2022/singapore-fintech-pace-acquires-bnpl-firm-rely/ and the website link is https://payrely.com/

We are already tracking Pace - https://www.wappalyzer.com/technologies/payment-processors/pace/ so maybe we can just update Pace

**Comment by rockeynebhwani** [comment]
.
