### ISSUE TITLE
Track 'Upptime'

### ISSUE THREAD

**Issue by John4266** [wappalyzer/wappalyzer#6094]
Vendor Site - https://upptime.js.org/
Category - Issue Trackers
Example Site - https://status.kitsune.tv/

**Comment by nurbek91** [comment]
still required

**Comment by nurbek91** [comment]
Hey @John4266 ,

Vigil status page
https://status.crisp.chat/

Upptime status page
https://demo.upptime.js.org/

Your example
Vigil status page
https://status.kitsune.tv/
Upptime issue tracker?
https://beta.kitsune.tv/

**Comment by John4266** [comment]
> Hey @John4266 ,
> 
> Vigil status page [status.crisp.chat](https://status.crisp.chat/)
> 
> Upptime status page [demo.upptime.js.org](https://demo.upptime.js.org/)
> 
> Your example Vigil status page [status.kitsune.tv](https://status.kitsune.tv/) Upptime issue tracker? [beta.kitsune.tv](https://beta.kitsune.tv/)

Hi.
Apparently they've changed the issue tracking technology on their website; however by the time i sent this Issue, they were using Upptime.

In that case, I would recommend adding both technologies anyway.
Should i make a different issue for Vigil?

**Comment by nurbek91** [comment]
@John4266 thanks mate, not required.
I'll try to add both.

**Comment by John4266** [comment]
@nurbek91 btw do you mind telling me how do you find other sites with the same technology that i post?

**Comment by nurbek91** [comment]
> @nurbek91 btw do you mind telling me how do you find other sites with the same technology that i post?

https://publicwww.com/websites/%22RocketLazyLoadScripts%22/

**Comment by John4266** [comment]
Thanks 👍
aight ima close now
