### ISSUE TITLE
Track Stencil

### ISSUE THREAD

**Issue by housseindjirdeh** [wappalyzer/wappalyzer#6132]
- Vendor Site: https://stenciljs.com/
- Category: Web frameworks
- Example Sites: 
  - [Ionic HN](https://corehacker-10883.firebaseapp.com/)
  - [Ionic Beer](https://stencilbeer.firebaseapp.com/)
  - [InstaMusic](https://instamusic-c15fe.firebaseapp.com/)
 - Detection method: Not sure since [`window` namespaces have been removed](https://github.com/ionic-team/stencil/blob/main/BREAKING_CHANGES.md#windownamespace-is-no-longer-a-thing). Maybe search for `stencil-` elements in the DOM?

**Comment by adamdbradley** [comment]
One additional check is that Stencil will always add a `hydrated` class to the `<html>`. 
![image](https://user-images.githubusercontent.com/452425/164277545-87761219-5d53-4dfd-9c5c-9d67f8712193.png)

**Comment by nurbek91** [comment]
.

**Comment by AliasIO** [comment]
Added, thanks!
