### ISSUE TITLE
Track Solid.js

### ISSUE THREAD

**Issue by housseindjirdeh** [wappalyzer/wappalyzer#6133]
- Vendor Site: https://www.solidjs.com/
- Category: JavaScript frameworks
- Example Sites: 
  - [Solid HN](https://hackernews-csr.ryansolid.workers.dev/)
  - [RealWorld](https://solidjs.github.io/solid-realworld/)
 - Detection method: Not sure 🤔

**Comment by nurbek91** [comment]
Hey @housseindjirdeh , thanks for this request.
We were unable to complete the request with the information provided.
If they could add the __solid property that would be perfect.
There have been many requests already for this technology.
I also personally asked the community in the discord channel to add some property.

**Comment by housseindjirdeh** [comment]
Noted, thank you! I wasn't aware that many folks have already made the request to track SolidJS, so I'm sorry for opening an additional issue  :)
