### ISSUE TITLE
Track 'Shoefitr'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#6142]
Vendor site - https://www.shoefitr.io/
Category - Personalisation
Example Site - https://www.magcreativefootwear.com/megamok-4001m-black-black.html
Detection - Look for `<a> `tag with `HREF` pointing to domain  'https://api.shoefitr.io/'

**Comment by rockeynebhwani** [comment]
Still required

**Comment by nurbek91** [comment]
only 1 website. very low latency
