### ISSUE TITLE
Improve 'Algolia' Detection

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#6145]
Site where it's not working - https://rothys.com/

Depending on the type of integration, Algolia creates different JS objects...  We can improve this by looking for following JS objects -

- `__GLOBAL__.algolia.AppId`
- `__GLOBAL__.algolia.ApiKey`

**Comment by rockeynebhwani** [comment]
@nurbek91 - Some more sites using Algolia but not getting detected -

Another example site - https://www.allbirds.com/products/womens-tree-skippers-lux-purple?size=7

In such cases, we need to look for 'search-insights' JS from location (https://cdn.jsdelivr.net/npm/search-insights@2.0.3). Extract version from this. OR we can check for 'AlgoliaAnalytics' JS object

**Comment by rockeynebhwani** [comment]
@AliasIO - Can we keep this open to take care of my last comment?

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , 
Maybe we can create a separate technology Algolia Insights?
![image](https://user-images.githubusercontent.com/3456008/164949552-8ab15126-c2d8-45be-ad3b-1e346a0196e7.png)
https://github.com/algolia/search-insights.js

**Comment by rockeynebhwani** [comment]
@nurbek91 - Algolia Insights is not a separate product. It's used along with 'Algolia Search' OR 'Algolia Recommend'.
