### ISSUE TITLE
Track 'Amazon Buy With Prime'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#6152]
Amazon announced this yesterday - https://buywithprime.amazon.com/home

Vendor site - https://buywithprime.amazon.com/home
Category - Miscellaneous 
Example Site - https://www.myredtea.com/products/my-red-tea-organic-rooibos-80-tagless-teabags-200g-6-8oz
Detection - Look for IFRAME with source '//order.buywithprime.amazon.com/'

**Comment by rockeynebhwani** [comment]
.

**Comment by nurbek91** [comment]
Hey mate, very low latency
