### ISSUE TITLE
Improve detection of 'Instant.page'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#6153]
Initially added as part of https://github.com/wappalyzer/wappalyzer/issues/4331

Site where detection is not working - https://www.greeneroom.ie/collections/color-wow/products/color-wow-dream-filter-250mls

We can also look for 'hs-instantload.min.js' (HyperSpeed uses Instant.page and this is the JS which we can look for)

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , maybe add for HyperSpeed implies Instant.Page?

**Comment by rockeynebhwani** [comment]
@nurbek91 yes.. I think we can do that

**Comment by nurbek91** [comment]
> @nurbek91 yes.. I think we can do that

done here https://github.com/wappalyzer/wappalyzer/pull/6175/files
