### ISSUE TITLE
Track 'PhotoSwipe' JS library

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#6174]
Vendor site - https://photoswipe.com/
Category - Javascript Libraries
Example Site - https://www.poochandmutt.co.uk/products/calm-relaxed-dry-food
Detection - Look for script '//cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.3/photoswipe.min.js'

**Comment by rockeynebhwani** [comment]
Still required

**Comment by nurbek91** [comment]
https://wordpress.org/plugins/search/photoswipe/ 
photoswipe based wp plugins
