### ISSUE TITLE
Track 'ReturnPrime'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#6185]
Vendor site - https://www.returnprime.com/
Category - Returns
Example Site - https://neemans.com/apps/return_prime
Detection - Look for script from domain '//return-prime-proxy-prod.s3.ap-south-1.amazonaws.com/'

**Comment by rockeynebhwani** [comment]
Still required

**Comment by rockeynebhwani** [comment]
.

**Comment by dhavalveera** [comment]
@rockeynebhwani - can you please share the other examples as well apart from what you've mentioned above? as above-mentioned example isn't working for me

**Comment by dhavalveera** [comment]
@rockeynebhwani `ReturnPrime` has been added and will be traced in the new release, you can close the Issue. Thanks

**Comment by rockeynebhwani** [comment]
Thanks @dhavalveera
