### ISSUE TITLE
Track 'Rumble'

### ISSUE THREAD

**Issue by John4266** [wappalyzer/wappalyzer#6205]
Vendor Site - https://rumble.com/
Category - Video Players
Example Site - https://www.baba-mail.co.il/quizzes/quiz.aspx?quizid=39

**Comment by John4266** [comment]
still needed

Detection:
`<iframe id="player_200" allowfullscreen="" class="rumble" src="https://rumble.com/embed/*" __idm_id__="44892161" width="730" height="550" frameborder="0"></iframe>`

`iframe` element with class attribute of `rumble` and src containing `https://rumble.com/embed/*`

Do note that this element for example (in this case, in the aforementioned website) appeared dynamically and didn't appear until some Javascript injected it.

**Comment by nurbek91** [comment]
Hey mate, do you know what traces of this technology mean on these sites.
https://www.teimporta.com/
https://nerdheist.com/
http://viralmundo.nl/karaoke-zingen-op-podium/
https://www.godupdates.com/saved-five-children-nicholas-bostic/

**Comment by John4266** [comment]
Hi,
I've no idea what these sites are using Rumble/"Rumble Swap" for, but they definitely does not seem to be using it for the video embedding.
Therefore, tracking specifically an `iframe` element with the attributes mentioned above might be more accurate.

**Comment by nurbek91** [comment]
> Hi, I've no idea what these sites are using Rumble/"Rumble Swap" for, but they definitely does not seem to be using it for the video embedding. Therefore, tracking specifically an `iframe` element with the attributes mentioned above might be more accurate.

Ok thanks mate,  did so, `"Rumble.resize"` only works where there is a video player as well.
