### ISSUE TITLE
Inconsistent response from NPM vs API endpoint /v2/lookup

### ISSUE THREAD

**Issue by amblasingame** [wappalyzer/wappalyzer#6240]
**Platform**
Which platform does the bug apply to?
* NPM
* API endpoint 

**Describe the bug**
There is a difference in responses for the same website using the NPM module command ```wappalyzer```  vs the API endpoint ```/v2/lookup```

**To Reproduce**
1. Install the NPM module using the directions [here](https://github.com/wappalyzer/wappalyzer/tree/master/src/drivers/npm) in the README
2. From the CLI run ```wappalyzer https://www.hulu.com -P```
3. Using curl, run ```curl --location --request GET 'https://api.wappalyzer.com/v2/lookup?urls=https://www.hulu.com&recursive=true' \
--header 'x-api-key: YOUR_KEY_HERE' | json_pp ```
4. Compare the two outputs

**Expected behavior**
I'm not sure if the different output is expected behavior or not. I wouldn't think the two should return different outputs. I need to understand what to expect from the API and NPM to correctly implement logic in a ticket I am working on.

**Additional context**
Here is a snippet comparing the two outputs. I used **<-- different** on the NPM snippet to show additional fields being returned.

**Using NPM**
```
"urls": <-- different {
    "https://www.hulu.com/": {
      "status": 302
    },
    "https://www.hulu.com/welcome": {
      "status": 200
    }
  },
...json omitted for brevity...
{
      "slug": "node-js",
      "name": "Node.js",
      "confidence": 100, <-- different
      "version": null,
      "icon": "node.js.png",
      "website": "http://nodejs.org",
      "cpe": "cpe:/a:nodejs:node.js", <-- different
      "categories": [
        {
          "id": 27,
          "slug": "programming-languages",
          "name": "Programming languages"
        }
      ]
}
```
***
**Using /v2/lookup**
```
"url": "https://www.hulu.com",
...json omitted for brevity...
{
                "slug": "node-js",
                "name": "Node.js",
                "versions": [],
                "trafficRank": 26670,
                "confirmedAt": 1651363055,
                "categories": [
                    {
                        "id": 27,
                        "slug": "programming-languages",
                        "name": "Programming languages"
                    }
                ]
}
```

**Comment by AliasIO** [comment]
It's by design. The Lookup API doesn't return results with a confidence less than 100 or `null` values and returns additional [fields](https://www.wappalyzer.com/docs/fields/). The `cpe` field isn't currently being included. We could add it but it's not that well maintained, most technologies don't have it.

The technologies may differ too as API returns cached results by default. Passing `live=true` will yield results more in line with the Node.js module.

**Comment by amblasingame** [comment]
Ok! I wasn't aware there were differences between the two. I didn't see it called out in the documentation. I'll close the issue since it's by design.
