### ISSUE TITLE
Track 'Skio'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#6260]
Vendor site - https://skio.com/
Category - Shopify Apps / Subscriptions (There is no such category but I think we should have a category for subscriptions.. this can contain solutions like 'Recharge' and many others)
Example Site - https://overtone.co/collections/all
Detection - Look for script from domain '//cdn.skio.com/'

Also see - https://github.com/wappalyzer/wappalyzer/issues/5956

**Comment by nurbek91** [comment]
.
