### ISSUE TITLE
Track 'Next Total' Ecommerce platform

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#6265]
Vendor site - https://www.next.co.uk/
Category - Ecommerce
Example Site - https://www.reiss.com/ OR https://www.next.co.il/
Detection - Look for script from domain '//api.e.nextdirect.com/'

Please note that 'Next Total' platform is new and you won't find many examples in the wild as of now. Also NEXT is a retailer which is developing TOTAL platform for other retailers.. I couldn't find a separate site for NEXT TOTAL.

See press release - https://www.drapersonline.com/news/nexts-total-platform-growth-currently-constrained#:~:text=Next%20CEO%20Lord%20Wolfson%20has,Total%20Platform%20service%20from%202023.&text=In%20the%20six%20months%20to,and%2062%25%20against%202020).

**Comment by nurbek91** [comment]
.
