### ISSUE TITLE
Got an error when initiate Wappalyzer.latest()

### ISSUE THREAD

**Issue by HeangSok** [wappalyzer/wappalyzer#6276]
Good morning, sir. 
When I try to initiate this code in python like this:
from Wappalyzer import Wappalyzer, WebPage
wappalyzer = Wappalyzer.latest()

it returns a warning now.  3 months ago it was working fine. 
May you tell me what should I do to make it work?

Best regards
Heang

**Comment by AliasIO** [comment]
Please report this with the author of the Python fork you're using.
