### ISSUE TITLE
Track 'Cloudflare Rocket Loader'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#6283]
Vendor site - https://support.cloudflare.com/hc/en-us/articles/200168056-Understanding-Rocket-Loader
Category - Performance
Example Site - https://www.harrods.com/ OR https://www.mackintosh.com/gb/man
Detection - Look for request for JS 'rocket-loader.min.js'. You will have to check network requests for this. This doesn't appear in page source.

**Comment by rockeynebhwani** [comment]
.

**Comment by nurbek91** [comment]
>  This doesn't appear in page source.
It seems that  found js objects by which we can identify . Thanks
