### ISSUE TITLE
Tailwind not reliably detected

### ISSUE THREAD

**Issue by Immortalin** [wappalyzer/wappalyzer#6294]
**Platform**
Which platform does the bug apply to?
* Website

**Describe the bug**
https://murmel.social appears to use tailwind https://builtwith.com/murmel.social but Wappalyzer isn't detecting it.

**Comment by nurbek91** [comment]
Hey mate, fixed, thanks!
![image](https://user-images.githubusercontent.com/3456008/187069059-d96ee046-6164-48c1-9267-a073b6317a6f.png)
