### ISSUE TITLE
Track 'TryNow'

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#6299]
Vendor site - https://www.trynow.io/
Category - Miscellaneous 
Example Site - https://www.koio.co/products/torino-sesame-mens?variant=41962070933673 
- https://shopcuup.com/products/the-balconette-mesh-ultramarine?variant=39727864971330
Detection - Look for JS object 'trynowEnabled'

**Comment by rockeynebhwani** [comment]
.

**Comment by nurbek91** [comment]
Hey mate, added to the bnpl category, remotely suitable
![image](https://user-images.githubusercontent.com/3456008/193542539-5ee4e66a-7d2d-4d7c-9e96-3885d7dc7c5c.png)
