### ISSUE TITLE
Track `petite-vue`

### ISSUE THREAD

**Issue by manniL** [wappalyzer/wappalyzer#6320]
* Vendor Site: https://github.com/vuejs/petite-vue
* Category: JavaScript frameworks
* Example Sites:
	* https://daverupert.com/bookshelf
* Detection methods:
** HTML body regex - `<[^>]+v-scope[^<]+`  (similar to #3056)

**Comment by nurbek91** [comment]
Hey @manniL , added this technology, could you tell me that if the site uses petite-vue, then this means that it uses Vue.js?

**Comment by manniL** [comment]
Hey @nurbek91. No, `petite-vue` is just a subset of Vue and I would not count it as "running Vue.js" itself because the two techs are a little different. See [the repo](https://github.com/vuejs/petite-vue) and [my slides](https://petite-vue.lichter.io/19) for more details.

**Comment by AliasIO** [comment]
Thanks!
