### ISSUE TITLE
The wappalyzer extension slows down websites enormously

### ISSUE THREAD

**Issue by seirdotexe** [wappalyzer/wappalyzer#6353]
**Platform**
Which platform does the bug apply to?
* WebExtension (v6.10.26) (Firefox v101.0 (64-bit))

**Describe the bug**
The wappalyzer extension slows down websites enormously, especially on websites like Teams and Youtube.

**To Reproduce**
1. Enable the wappalyzer extension
2. Go to Teams web or Youtube
3. Endure the horrible loading time

**Expected behavior**
The wappalyzer extension shouldn't slow down websites.

**Additional context**
This always happens unless you disable the extension. You can see how Teams/Youtubes struggles to load until wappalyzer is done.

**Edit**
It seems like this happens due to uBlock Origin being enabled at the same time.

**Comment by seirdotexe** [comment]
On a portable version of Firefox with no other changes made besides installing the extension, Youtube doesn't seem to slow down. However, when you also install uBlock Origin with no other changes, Youtube becomes very slow. @Deckluhm Are you using uBlock Origin as well?

Tested using Portable Firefox v101.0.1.

**Comment by Deckluhm** [comment]
> On a portable version of Firefox with no other changes made besides installing the extension, Youtube doesn't seem to slow down. However, when you also install uBlock Origin with no other changes, Youtube becomes very slow. @Deckluhm Are you using uBlock Origin as well?
> 
> Tested using Portable Firefox v101.0.1.

I do.

**Comment by seirdotexe** [comment]
> I do.

Could you try disabling uBlock Origin and see if the issue is resolved on the websites that slow down for you?

**Comment by Deckluhm** [comment]
> > I do.
> 
> Could you try disabling uBlock Origin and see if the issue is resolved on the websites that slow down for you?

I have been testing disabling uBlock and enabling Wappalyzer and it's indeed faster.

**Comment by seirdotexe** [comment]
Seems like this isn't something we can fix. I'm definitely *not* disabling my adblock.

**Comment by AliasIO** [comment]
I use Firefox with uBlock Origin and haven't seen this happen. Are you using any non built-in lists?

**Comment by seirdotexe** [comment]
@AliasIO 

As I've stated in my earlier reply:

> On a portable version of Firefox with no other changes made besides installing the extension, Youtube doesn't seem to slow down. However, when you also install uBlock Origin with no other changes, Youtube becomes very slow.

**Comment by AliasIO** [comment]
@seirdotexe That would be great, you can email me at elbert@wappalyzer.com.

**Comment by AliasIO** [comment]
Added a potential fix in a8f64ee5661b521656ed9175d6c4c6687dce7e6a, please try loading the extension from source to see if it solved the performance issue.

**Comment by seirdotexe** [comment]
I just tested it out on Youtube and Teams and I'm receiving no further slowdowns anymore. Seems like it's working fine now, thank you very much!

**Comment by AliasIO** [comment]
Great, thanks for your help on this. :)

**Comment by seirdotexe** [comment]
After using Wappalyzer again for a while, I'm still noticing slowdowns, especially on YouTube. It's not as bad as before, but it's still noticeable when the extension is enabled.

**Comment by seirdotexe** [comment]
Apparently, I forgot to reopen the issue.

**Comment by AliasIO** [comment]
You can turn Wappalyzer off per website, hit the switch in the extension popup:

<img width="190" alt="Screen Shot 2022-08-10 at 8 12 17 am" src="https://user-images.githubusercontent.com/77259/183771004-a08a9dc1-2f85-4b66-86ff-e3bbb67e49e0.png">

If you can, please send me another performance test result and I'll have a look again.

**Comment by seirdotexe** [comment]
Thanks! I didn't know about that. I also just sent you an email with the performance test result.

**Comment by AliasIO** [comment]
@seirdotexe I had a look at your result and it looks pretty normal. I get a similar result (about 1 second of high CPU usage 3 seconds into loading the page). For me it doesn't result into noticeable delays but I'm on a M1 MacBook Pro. The high CPU usage is because of the large number of regular expressions that are being run, which is required for the extension to work. If it's causing issues on YouTube I'd suggest keeping it disabled there.

**Comment by seirdotexe** [comment]
@AliasIO Hey thanks for taking a look. I'll disable the extension on YouTube from now on. Once again thank you so much for your help!
