### ISSUE TITLE
Track 'Magewire'

### ISSUE THREAD

**Issue by wpoortman** [wappalyzer/wappalyzer#6409]
Magewire is a Laravel Livewire open-source port for Magento 2. It uses the JS lib (unmodified) from Livewire where the full backend logic is completely rewritten from the ground up. Currently, on each site where Magewire is used, Wappalyzer will identify Laravel Livewire. I've been looking for a solution to make a PR, but can't quite figure out how to make it see Magewire instead of Livewire.

Repo: https://github.com/magewirephp/magewire

Any ideas are welcome, would love to help!

**Comment by AliasIO** [comment]
Thanks!
