### ISSUE TITLE
Track Nextcloud

### ISSUE THREAD

**Issue by AndreBaumeier** [wappalyzer/wappalyzer#6442]
Nextcloud appears to have been added once, but seems not to be in this repo anylonger.

I followed up on the old merge request and fixed the regex as the detection rule changed.

this works for me:

```
<script[^>]*>.*_oc_config={[^}]*"version":"([\d.]+)"
```

demo site is at https://demo1.nextcloud.com/login

OLD PR: https://github.com/wappalyzer/wappalyzer/pull/2911

OLD issue: #2863

**Comment by AliasIO** [comment]
Added, thanks!
