### ISSUE TITLE
Extend tracking for OXID eShop

### ISSUE THREAD

**Issue by AndreBaumeier** [wappalyzer/wappalyzer#6443]
OXID eShop and maybe OXID eShop Community Edition are not matched properly.

checking for a specific (frequently used module) could help.

path of js file contains `/modules/ddoe/visualcms/`

**Comment by nurbek91** [comment]
Wherever there are these traces, technology is detected
https://www.edeka24.de/
https://www.poetschke.de/
https://riess-ambiente.net/
https://www.a-n-a.com/shop/
https://www.froelichundkaufmann.de/
