### ISSUE TITLE
Name correction in Release Notes [Tangled Network]

### ISSUE THREAD

**Issue by dipakparmar** [wappalyzer/wappalyzer#6460]
In the recent release, Tangled Network got added, thanks for that. 

In the release notes, it has typo:  **~Tanged detection~** correct is **Tangled Network detection**
![Shot 2022-07-01 at 20 01 35@2x](https://user-images.githubusercontent.com/24366206/176984366-b8d4d043-0a37-427f-b907-307bc7e0c639.png)

`ADD Tanged detection`

**Comment by AliasIO** [comment]
I'll fix that, thanks!
