### ISSUE TITLE
Have the CLI tool support custom headers and cookies

### ISSUE THREAD

**Issue by ra1nb0rn** [wappalyzer/wappalyzer#6480]
**Is your feature request related to a problem? Please describe.**
Using the provided CLI tool (*src/drivers/npm/cli.js*), it is not possible to analyze page content that is blocked by an authentication mechanism. The reason for this is that it's not possible to supply custom headers or cookies to the tool.

**Describe the solution you'd like**
It would be great if custom headers and cookies could be supplied to the CLI tool via additional command line arguments. Ideally, this would be similar to the *curl* tool, where you can supply additional headers with ``-H`` and cookies with ``-b``. The supplied headers and cookies should then be used within all wappalyzer requests to pass authentication mechanisms when analyzing a web page.

**Describe alternatives you've considered**
N/A

**Additional context**
This feature request is somewhat similar to #3214. The difference is that I would request this to be implemented into the CLI tool and not (just) the wappalyzer library.

**Comment by AliasIO** [comment]
Added in 8ec975cc99d1ba08ebcff0cabb5d430608a51cb7.

You can pass cookies as headers:

```shell
node cli.js https://www.example.com -H "Authorization: Basic abc" -H "Cookie: user=admin"
```
