### ISSUE TITLE
Track 'SunAdNetwork'

### ISSUE THREAD

**Issue by John4266** [wappalyzer/wappalyzer#6483]
Vendor Site - https://www.sunadnetwork.com/
Category - Advertising
Example Site - https://coursesbits.com/course/c-2022-complete-training-course
`<script src="https://adstrack2.com/ppc/*"></script>`

**Comment by nurbek91** [comment]
Hey @John4266 
Few examples. Is it worth adding it
https://publicwww.com/websites/%22adstrack2%22/

**Comment by John4266** [comment]
On second thought, it does appear to be infrequently used.
