### ISSUE TITLE
'osTicket' is not detected

### ISSUE THREAD

**Issue by John4266** [wappalyzer/wappalyzer#6506]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome & Mozilla Firefox)

**Describe the bug**
Wappalyzer doesn't detect osTicket in the following sites:
https://www.malinc.com/helpdesk/
https://tickets.iwin.co.il/index.php

**To Reproduce**
open any of the sites above and check wappalyzer

**Expected behavior**
Should detect osTicket

**Comment by DavidKessel** [comment]
it works for me on both websites.

**Comment by noammiz007** [comment]
I just checked again and it only seems to work for me on Chrome.
The extension seems to really have something against Firefox 😅

Firefox 104.0b2 (64-bit) | Extension Version: 6.10.38

malinc.com test:
![qCVzEoiyHU](https://i.imgur.com/ja4W4BB.png)

iwin.co.il test:
![](https://i.imgur.com/1zxqslH.png)

---

Chrome 103.0.5060.134 (Official Build) (64-bit) | Extension Version: 6.10.36

malinc.com test:
![qCVzEoiyHU](https://i.imgur.com/zTG1KuG.png)

iwin.co.il test:
![](https://i.imgur.com/fwJfFqH.png)

**Comment by John4266** [comment]
I just checked again and it only seems to work for me on Chrome.
The extension seems to really have something against Firefox 😅

Firefox 104.0b2 (64-bit) | Extension Version: 6.10.38

malinc.com test:
![qCVzEoiyHU](https://i.imgur.com/ja4W4BB.png)

iwin.co.il test:
![](https://i.imgur.com/1zxqslH.png)

---

Chrome 103.0.5060.134 (Official Build) (64-bit) | Extension Version: 6.10.36

malinc.com test:
![qCVzEoiyHU](https://i.imgur.com/zTG1KuG.png)

iwin.co.il test:
![](https://i.imgur.com/fwJfFqH.png)

**Comment by nurbek91** [comment]
Hey @John4266, installed specially the browser and the extension everything works fine for me
Firefox 104.0b2 (64-bit) | Extension Version: 6.10.39 ☑
Chrome 103.0.5060.134 (Official Build) (64-bit) | Extension Version: 6.10.39 ☑
