### ISSUE TITLE
patch notes / update notes won't turn off ...

### ISSUE THREAD

**Issue by Wilfried-1** [wappalyzer/wappalyzer#6522]
**Platform**
Which platform does the bug apply to?
* WebExtension G Chrome

**Describe the bug**
Eah time i open chrome there is another tab that opens itself displaying the latest update notes...

**To Reproduce**
1. Go to 'Wappalyzer options
2. Click on 'display updates
4. quit
5. refresh and see that display updates is still checked...

**Expected behavior**
If i uncheck display updates notes then i would like 'display update notes' to be unchecked and thet there is no tab that is opening itself as the opening of chrome...

**Comment by nurbek91** [comment]
Hey @Wilfried-1 , Is there still a problem?

**Comment by Wilfried-1** [comment]
> Hey @Wilfried-1 , Is there still a problem?

Yes unfortunately...

**Comment by AliasIO** [comment]
Is this an issue with v6.10.43 still? Are any options being saved when you change them in the extension settings?
