### ISSUE TITLE
Improvement of the moodle detection

### ISSUE THREAD

**Issue by tarraschk** [wappalyzer/wappalyzer#6529]
Hello,

Moodle identification is quite limited on recent versions linked to branche 3.6.X or higher. This is caused by the actual regex used.

An improvement could come from exploring URLs <WEBSITE>/lib/upgrade.txt which actually show the versions of the target with full changelog.

An example is available here: https://lms.sulb.uni-saarland.de/moodle/lib/upgrade.txt (found through Google dorks)

Could we work on an improvement on that?

**Comment by nurbek91** [comment]
Hey @tarraschk , but the technology is defined without additional changes to the current code. Can you provide links where it doesn't work?
![image](https://user-images.githubusercontent.com/3456008/190477572-96f30eb3-7dc9-46b0-ad71-452e35931448.png)

**Comment by nurbek91** [comment]
If you offer to go inside the file and take the version, it is rather inefficient, no one will open this file using this link

**Comment by tarraschk** [comment]
Hello @nurbek91 sorry for the delay 😃 

The issue here is that when going on the https://lms.sulb.uni-saarland.de/moodle/ url we do not have the version of the Moodle software.

As shown on your screenshot, Moodle is detected, but not its version.

I suggested that in such cases we trigger a request to the /lib/upgrade.txt file as it does contain this information.

Would that be something okay for the WappAlyzer team? If so I would be okay to make the Pull Request.

**Comment by tarraschk** [comment]
@nurbek91 would you be okay with my suggestion?

**Comment by AliasIO** [comment]
@tarraschk The extension does not make network requests of its own. We want to avoid making numerous requests in the background every time a website is visited.
