### ISSUE TITLE
Not enough CPE for All in one SEO products.

### ISSUE THREAD

**Issue by wild0ni0n** [wappalyzer/wappalyzer#6586]
**Platform**
* WebExtension (Google Chrome, Mozilla Firefox)
* NPM
* Bookmarklet
* Website

**Describe the bug**
Not enough CPE for All in one SEO products.
Please also support vendor `aioseo`.

Specific CPE: 
`cpe:2.3:a:aioseo:all_in_one_seo:*:*:*:*:*:wordpress:*:*`

https://github.com/wappalyzer/wappalyzer/blob/e764b80e12c686834b030870dbbf986f7478207c/src/technologies/a.json#L2163

**Comment by AliasIO** [comment]
Thanks! I'll update that.
