### ISSUE TITLE
'UptimeRobot' is not detected

### ISSUE THREAD

**Issue by John4266** [wappalyzer/wappalyzer#6632]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome, Mozilla Firefox)
* Website

**Describe the bug**
Wappalyzer doesn't recognize `UptimeRobot` on the following sites:
https://status.jumbomail.me/
https://status.starkrdp.io/

**To Reproduce**
1. Go to https://status.jumbomail.me/ or https://status.starkrdp.io/
2. Check wappalyzer

**Expected behavior**
It should detect

**Additional context**
Under the `head` tag, there is a `link` tag with `href` attribute pointing to `https://userfiles.uptimerobot.com/img/000000-0000000000-icon.png`
it might be possible to look for `https://userfiles.uptimerobot.com/img` to fix the detection

**Comment by nurbek91** [comment]
Hey @John4266 thanks for detailed request , this one should be already fixed here #6694
