### ISSUE TITLE
Rain Details CRM not detected

### ISSUE THREAD

**Issue by vfcampo** [wappalyzer/wappalyzer#6656]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome, Mozilla Firefox)
* API

**Describe the bug**
This website is using Rain Details (https://www.rainpos.com/) CRM but we are not able to detect them. Here's the image with the scripts to be found.
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/55451462/185248822-80ba1ad7-a2c3-4164-9976-2b83983e394c.png">
```
<script type="text/javascript" src="https://images.rainpos.com/jquery.tools.min.js" attr="nomove"></script>
<script type="text/javascript" src="https://images.rainpos.com/jquery-migrate-1.2.1.min.js" attr="nomove"></script>
<script type="text/javascript" src="https://images.rainpos.com/json2.js" attr="nomove"></script>

<!-- reverts jquery to 1.3.2 
    <script type="text/javascript" src="https://images.rainpos.com/jquery.tools.min.js" attr="nomove"></script>
    -->



```

**To Reproduce**
1. Go to https://www.closetohomestores.com/ 
2. Click on the Chrome extension 
4. See error: missing info
5.

**Expected behavior**
We should be able to find the CRM Data in the ecommerce category

**Additional context**

**Comment by vfcampo** [comment]
Thank  you Elbert

**Comment by AliasIO** [comment]
Cheers!
