### ISSUE TITLE
Improve 'Amplitude' detection

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#6701]
Site where detection is not working - https://rothys.com

Look for script with path - //cdn.segment.com/next-integrations/actions/amplitude-plugins/

When Amplitude is integrated via Segment, this file will be present.

**Comment by nurbek91** [comment]
Hey @rockeynebhwani , thanks!!
Updated, but locally could not test the file is not loaded. Should work if opened through a browser probably
