### ISSUE TITLE
Track 'Laravel Support Bubble'

### ISSUE THREAD

**Issue by John4266** [wappalyzer/wappalyzer#6787]
Vendor Site - https://github.com/spatie/laravel-support-bubble
Category - Live Chat
Example Site: https://ohdear.app
Detection - Find `div` elements with any of the following classes:
`spatie-support-bubble__form`
`spatie-support-bubble__response`
or any `div` with a class that starts with `spatie-support-bubble`

**Comment by nurbek91** [comment]
Hey @John4266 ,
Can we say that if this technology is present, then the site is made on Laravel?

**Comment by John4266** [comment]
> Hey @John4266 , Can we say that if this technology is present, then the site is made on Laravel?

Well I am not quite sure if the live chat module requires the site to be made with Laravel (I don't know much about laravel/php so I might be wrong), but it definitely seems to require PHP.
