### ISSUE TITLE
Track 'Cachet'

### ISSUE THREAD

**Issue by John4266** [wappalyzer/wappalyzer#6809]
Vendor Site - https://cachethq.io/
Category - Issue Trackers
Example Sites:
https://demo.cachethq.io/
https://status.vrchat.com/
https://status.letshost.ie/
Detections - So far the only detections i've found are the following:
1. `script` tag with `src` attribute pointing to `/dist/js/all*.js`
2. checking if a function called `askConfirmation` exists
3. check if both of the following `meta` tags exist:
`<meta name="env" content="production">`
`<meta name="token" content="RANDOM-STRING-HERE">`

**Comment by mrinc** [comment]
https://github.com/CachetHQ/Cachet/issues/4326   

Cachet is basically outdated (well the current version) - so might be a good idea to wait for next path to be taken (ref above issue).  
That way we could just get them to add a meta generator tag to the html output to make it easier and more accurate to verify this.
