### ISSUE TITLE
Track "h2o" Webserver

### ISSUE THREAD

**Issue by libDarkstreet** [wappalyzer/wappalyzer#6826]
Website: https://h2o.examp1e.net/ (this is the official website)
Github: https://github.com/h2o/h2o

 Detection: Server header containing the word h2o.
 
 The version number usually appears in the server header like this: h2o/2.3.0
![Screenshot from 2022-10-09 19-07-12](https://user-images.githubusercontent.com/55440418/194775044-e09fa9fb-8158-49cc-8ba8-3142e5b6a13c.png)

**Comment by AliasIO** [comment]
Thanks!
