### ISSUE TITLE
React technology is incorrectly identified

### ISSUE THREAD

**Issue by nurbek91** [wappalyzer/wappalyzer#6906]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome, Mozilla Firefox)
* NPM

**Describe the bug**
This piece of code returns quite often false positive results.
`"html": "<[^>]+data-react",`

**To Reproduce**
`data-react-helmet`
https://sync.si/room/ASD/
`data-reactions-type`
https://www.turkanime.co/

**Expected behavior**
Should I remove this part or change it somehow?

**Additional context**
It would be great to get advice from react developers

**Comment by dhavalveera** [comment]
@nurbek91 - can you please share more details on this so it'll be very helpful to identify the issue & can be rectified.
