### ISSUE TITLE
After running, very many core.chrome.xx.xxx files will be generated

### ISSUE THREAD

**Issue by Mr-KIDBK** [wappalyzer/wappalyzer#6908]
![image](https://user-images.githubusercontent.com/52557540/196171983-e4b471cf-d2d6-42b2-bb56-4d3c7bcf9f1a.png)
Is there a configuration to avoid this problem？

**Comment by Spider-sun** [comment]
Not solved yet？

**Comment by gottlike** [comment]
FYI, I ran into the same issue with AWS Lambda: https://github.com/wappalyzer/wappalyzer/issues/6923

As a workaround I'm deleting those files after every request.

**Comment by cantonalex** [comment]
@Spider-sun sorry to hijack couldn't find any socials on your profile. Are you trying to run a lot of instances of wappalyzer?

**Comment by barbaniahra** [comment]
I've been facing the same. Trying to run several wappalyzer instances in the python:3.9-slim docker image.
