### ISSUE TITLE
Track 'CPABuild'

### ISSUE THREAD

**Issue by John4266** [wappalyzer/wappalyzer#6909]
Vendor Site - https://cpabuild.com/
Category - Surveys / Advertising / not sure to be honest
(This platform is used to hide content behind a Surveys "Locker", usually used by "untrustworthy looking" sites)
Example Sites:
https://hdmovies.one/ 
https://www.debridleech.com/
Detection: Check if a JS variable/function called `CPABuildLock` exists

**Comment by nurbek91** [comment]
Hey @John4266 , created request, but couldn't find examples
