### ISSUE TITLE
`require('wappalyzer/technologies.json')` no longer works

### ISSUE THREAD

**Issue by epicfaace** [wappalyzer/wappalyzer#6910]
I was using the following code with wappalyzer 6.3.11 to extend with our own custom technologies:

```
const data = require('wappalyzer/technologies.json');
const extraTechnologies = require('./technologies.json');

export const technologies = {
  ...data.technologies,
  ...extraTechnologies
};

setTechnologies(technologies);
setCategories(data.categories);
```

However, this no longer works because we have to import from a.json, b.json, etc. It would be nice if wappalyzer exported a `technologies` and `categories` JS object so we could just pull from those variables!

**Comment by AliasIO** [comment]
The driver is responsible for loading technologies. You can use something like this:
```javascript
const categories = JSON.parse(
  fs.readFileSync(path.resolve(`${__dirname}/categories.json`))
)

let technologies = {}

for (const index of Array(27).keys()) {
  const character = index ? String.fromCharCode(index + 96) : '_'

  technologies = {
    ...technologies,
    ...JSON.parse(
      fs.readFileSync(
        path.resolve(`${__dirname}/technologies/${character}.json`)
      )
    ),
  }
}
```

**Comment by epicfaace** [comment]
Thanks. It might be nice to export these from wappalyzer so that other libraries can just do `import technologies` or `import categories`. This way, if wappalyzer changes its implementation in the future to include more characters, then other clients don't have to change their code accordingly.
