### ISSUE TITLE
Wappalyzer extension keeps opening "Installation successful" window

### ISSUE THREAD

**Issue by AliHoussein** [wappalyzer/wappalyzer#6911]
**Platform**
* WebExtension (Brave Version 1.30.86 Chromium: 94.0.4606.61 (Official Build) (x86_64))
* Mac OS Big Sur 11.7

**Describe the bug**
Installed Wappalyzer from the Google Chrome Store. 
The extensions keeps opening https://www.wappalyzer.com/installed?utm_source=installed&utm_medium=extension&utm_campaign=wappalyzer
No options are saved. 

**To Reproduce**
One way that triggers the window to reopen :
1. Go to the Wappalyzer Icon
2. Click on Options and set the options : uncheck Tell me about upgrades and  Anonymously send identified technologies to wappalyzer.com
3. Close the tab
4. The "Installation successful" window reopens automatically as if a new installation has just been done.
5. Sometimes closing the "Installation successful" tab or some other tab reopens a new "Installation successful" tab. 

**Expected behavior**
The "Installation successful" should open only once at installation.

**Comment by AliasIO** [comment]
This should be fixed in today's update.
