### ISSUE TITLE
Memory and file leak on AWS Lambda

### ISSUE THREAD

**Issue by gottlike** [wappalyzer/wappalyzer#6923]
**Platform**
* NPM

**Describe the bug**

When deploying to AWS Lambda, Wappalyzer RAM usage grows with every request. Furthermore the ephemeral storage (`/tmp`) seems to grow, too. Apparently, when the `/tmp` folder reaches the configured limit, Wappalyzer inserts the error message `Navigation failed because browser has disconnected!` inside the results. When this limit is reached, only the DNS probe results will be returned, along with the error message.

RAM leak:
![image](https://user-images.githubusercontent.com/278766/197176415-cb8ef8f0-3ae8-481c-944b-299b7f317a29.png)

**To Reproduce**

Create an AWS Lambda function with 1024 MB RAM, 512 MB ephemeral storage and the following code:

```js
'use strict';

const Wappalyzer = require('wappalyzer');

const options = {
  debug: false, // Output debug messages
  delay: 0, // Wait for ms milliseconds between requests
  headers: {}, // Extra header to send with requests
  maxDepth: 1, // Don't analyse pages more than num levels deep
  maxUrls: 1, // Exit when num URLs have been analysed
  maxWait: 15000, // Wait no more than ms milliseconds for page resources to load
  recursive: false, // Follow links on pages (crawler)
  probe: true, // Perform a deeper scan by performing additional requests and inspecting DNS records
  proxy: false, // Proxy URL, e.g. 'http://user:pass@proxy:8080'
  userAgent:
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36',
  htmlMaxCols: 2000, // Limit the number of HTML characters per line processed
  htmlMaxRows: 3000, // Limit the number of HTML lines processed
  noScripts: false, // Disabled JavaScript on web pages
  noRedirect: false // Disable cross-domain redirects
};

exports.handler = async (event, context) => {
  let output = null;
  const wappalyzer = new Wappalyzer(options);

  const input = 'http://example.com';

  try {
    if (input) {
      const headers = {};
      const url = decodeURIComponent(input);

      await wappalyzer.init();
      const result = await wappalyzer.open(url, headers).analyze();

      output = { status: 200, body: result };
    } else {
      output = { status: 400, body: { errorMsg: 'No URL specified' } };
    }
  } catch (error) {
    console.error(error);
    output = { status: 500, body: { errorMsg: 'Internal server error' } };
  }

  await wappalyzer.destroy();

  return output;
};
```

**Expected behavior**
I expect Wappalyzer to "clean up" after every request on AWS Lambda.

**Comment by gottlike** [comment]
As I understand, you are using AWS Lambda, too @AliasIO. Don't you have the same issue, or am I doing something wrong?

**Comment by gottlike** [comment]
FYI, apparently chromium writes "core dumps" after every request to `/tmp`:

![image](https://user-images.githubusercontent.com/278766/197224403-aa083c50-b428-41e4-8cd8-f7d3002fe899.png)

Any idea how to prevent that?

**Comment by gottlike** [comment]
FYI: I found an ugly workaround by adding ` execSync('rm -f /tmp/core.*');` before the `return output;`.

**Comment by AliasIO** [comment]
On Lambda I re-use the Chromium instance between invokes, which looks something like this:

```javascript
let browser

const wappalyzer = new Wappalyzer(options)

if (browser) {
  wappalyzer.browser = browser
} else {
  await wappalyzer.init()

  browser = wappalyzer.browser
}
```

When the browser disconnects I reconnect it an re-run the request.

Running on Lambda works fine but I do encounter the 'Navigation failed because browser has disconnected!' error often when running a large number of consecutive requests on EC2. The error comes from Puppeteer. I hadn't made the connection with `/tmp` filling up.

**Comment by gottlike** [comment]
Good to know that I'm not the only one hitting that issue! Manually cleaning the `/tmp/core.*` files before returning will probably help you, too :)

**Comment by AliasIO** [comment]
I hope so, I'll be doing some testing!

**Comment by cantonalex** [comment]
@gottlike sorry to hijack couldn't find any socials on your profile. Are you trying to run a lot of instances of wappalyzer?

**Comment by gottlike** [comment]
@cantonalex This is just one instance inside a VM, running consecutive requests.

**Comment by cantonalex** [comment]
@gottlike any ideas for running 100's in parallel? My Twitter is @alexcanton if you're interested in chatting.

**Comment by gottlike** [comment]
@cantonalex Well, see my first post in this issue: Just use AWS Lambda. Cheapest and easiest way to scale massively. In case you wanted to sell something, not interested ;)

**Comment by cantonalex** [comment]
@gottlike How did you get chromium working on lambda with the file size? I've been looking at this https://github.com/alixaxel/chrome-aws-lambda

**Comment by gottlike** [comment]
@cantonalex I built a Docker image, since that doesn't have a size limit. I will spare you the trouble and give you my Dockerfile:

```Shell
FROM public.ecr.aws/lambda/nodejs:14

WORKDIR ${LAMBDA_TASK_ROOT}

COPY app.js package.json package-lock.json ./

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ENV CHROMIUM_BIN /usr/bin/chromium-browser
ENV CHROMIUM_ARGS "--user-data-dir=/tmp/chromium --single-process --no-sandbox --no-zygote --disable-gpu --ignore-certificate-errors --allow-running-insecure-content --disable-web-security"

RUN yum install -y amazon-linux-extras && \
    amazon-linux-extras install epel -y && \
    yum install -y chromium && \
    yum clean all && \
    npm ci

CMD [ "app.handler" ]
```

But you have to figure out the rest. This is not a general support thread 😆

**Comment by AliasIO** [comment]
@cantonalex You can also use a Lambda layer like the repo you linked to describes. To run many instances in parallel you can you use AWS Batch, we often run a thousand or more. :) We may already have the data you need, let me know if you want to tap into that rather than building out your own infrastructure.
