### ISSUE TITLE
Google Chorme WebExtension 6.10.44 - not displaing results

### ISSUE THREAD

**Issue by mattia8961** [wappalyzer/wappalyzer#6929]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome on Windows 11) version 6.10.44

**Describe the bug**
when in the Google Chrome extension option is disabled the option “Include cached detections in results”, on every website isn't displayed any results, but the counter shows that there are.

![Wappalyzer bug](https://user-images.githubusercontent.com/37270576/197735635-cd299ef4-7edc-4b46-8073-e2b0a2250486.png)

**To Reproduce**
1. Go to the extesion options
2. Disable “Include cached detections in results”
3. Go to any website

**Expected behavior**
Display the detections

**Additional context**
none

**Comment by nurbek91** [comment]
Hey @AliasIO, yes confirm issue I have the same problem, also received a couple of requests about this error

**Comment by AliasIO** [comment]
Fixed in 55682469134bae5b22eaab7a09dff6bc85ba7bb9, thanks!

**Comment by AliasIO** [comment]
Pushed v6.10.45 today.
