### ISSUE TITLE
New release not pushed to public NPM registry

### ISSUE THREAD

**Issue by gottlike** [wappalyzer/wappalyzer#6951]
According to the repo on Github, Wappalyzer is on version [6.10.43](https://github.com/wappalyzer/wappalyzer/releases), but the public NPM registry is still at [6.10.41](https://www.npmjs.com/package/wappalyzer).

**Comment by AliasIO** [comment]
v6.10.43 mainly included bug fixes for the WebExtension but they're all on v6.10.45 now. 👍
