### ISSUE TITLE
Wappalyzer Chrome extension breaks 'Backward/Forward Cache' sometimes

### ISSUE THREAD

**Issue by rockeynebhwani** [wappalyzer/wappalyzer#6952]
**Platform**
* WebExtension (Google Chrome)

**Describe the bug**
Chrome introduced the backward/forward cache in Dec-2021. More details here - https://web.dev/bfcache/. It's possible for some 3rd parties or chrome extensions to use techniques which may result in backward/forward cache not working for users browsing any given site. 

**To Reproduce**
This can happen on any site but I re-produced it on https://rothys.com while randomly browsing the site.  
Error reported is - Extensions with long-lived connection attempted to send messages to frames in back/forward cache. 

<img width="1255" alt="Screenshot 2022-11-02 at 13 09 51" src="https://user-images.githubusercontent.com/1718757/199498317-126dd1a3-71a0-4278-a02b-8b2ed87c5f7a.png">

You can see extension ID reported in DevTools belongs to Wappalyzer (See extension ID in the URL)

<img width="957" alt="Screenshot 2022-11-02 at 13 09 59" src="https://user-images.githubusercontent.com/1718757/199498327-992edca0-0045-4941-a273-5dde74e49ccf.png">

**Expected behavior**
When you test 'Backward/Forward' Cache from DevTools, pages should be restored from cache and there shouldn't be any errors attributed to Wappalyzer Chrome extension.

**Comment by AliasIO** [comment]
Does the extension actually break this functionality? The message says the page was not served from B/F cache because the back/forward button wasn't used to navigate.
