### ISSUE TITLE
Mantine and Turnstile support (if possible because idk how this work)

### ISSUE THREAD

**Issue by LoryPelli** [wappalyzer/wappalyzer#6957]
Add if possible support for recognize mantine on a website and for recognize new cloudflare thing: `Turnstile`

**Comment by LoryPelli** [comment]
Oh cloudflare turnstile it's supported...ok, thanks for this

**Comment by dhavalveera** [comment]
@LoryPelli - can you share 4 to 5 examples where this `mantine` is being used?

**Comment by LoryPelli** [comment]
> @LoryPelli - can you share 4 to 5 examples where this `mantine` is being used?

Mantine support has already been added

**Comment by nurbek91** [comment]
Hey @LoryPelli , Turnstile and mantine have been added recently. Is it possible to close this request or do you have any other wishes?

**Comment by LoryPelli** [comment]
> Hey @LoryPelli , Turnstile and mantine have been added recently. Is it possible to close this request or do you have any other wishes?

You can close it
