### ISSUE TITLE
Handling cookie compliance overlays

### ISSUE THREAD

**Issue by gottlike** [wappalyzer/wappalyzer#6960]
When analyzing this website with the NPM package: https://www.vwfs.de/

The NPM package is missing (at least) "Adobe Target", whereas the Chrome extension and the Wappalyzer SaaS find it. Tweaking the options (max columns, bytes analyzed) doesn't help.

**Comment by gottlike** [comment]
**Update:** When I disable "Include cached detections in results" in the extension, it also doesn't detect Adobe Target anymore.

I assume this is because Adobe Target only loads after visitors accept the cookie compliance overlay. Isn't there a way to automatically click "accept all" for (known) compliance overlays? Maybe that's a feature request.. ?

**Comment by gottlike** [comment]
Maybe data and logic from your [Demodal](https://github.com/AliasIO/demodal) extension could help, @AliasIO

**Comment by AliasIO** [comment]
Interesting idea. There's no standard way to accept cookies so maintaining a list to deal with all the various cookie banners will require a lot of maintenance. There are [some projects](https://www.npmjs.com/package/puppeteer-cmp-clicker) that attempt to do this that could be hooked into Wappalyzer if you wanted to.

**Comment by gottlike** [comment]
That definitely requires a manual and ongoing maintenance, like it's already done for the list of technologies. A longer lasting alternative to clicking DOM elements (that eventually change), would be to start a visit with the appropriate cookies/sessionStorage already set.

If that's not on your roadmap for Wappalyzer, I might create a module, similar to the project you linked to :)

**Comment by AliasIO** [comment]
A module is probably the way to go. You should be able to use the [`response`](https://github.com/wappalyzer/wappalyzer/blob/master/src/drivers/npm/driver.js#L709) event to hook it into Wappalyzer and modify the page before it's analysed.
