### ISSUE TITLE
Detected version of Elementor (Page Builder) is wrong

### ISSUE THREAD

**Issue by razvan-pricop-ptt** [wappalyzer/wappalyzer#6966]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome and Mozilla Firefox)

**Describe the bug**
When running the Wappalyzer extension on this website: https://aldamstreetart.it/ it detects Elementor as version 1.0.0. Although, in the page the script `frontend.min.js?ver=3.7.8` is present.

**To Reproduce**
1. Go to https://aldamstreetart.it/
2. Run the Wappalyzer extension
3. Scroll down to the Page Builder Category.
4. See `Elementor 1.0.0`

**Expected behavior**
I expected to see `Elementor 3.7.8`

**Additional context**
This probably happens because wappalyzer looks for the first javascript file that matches this regex: `"elementor/assets/js/[^/]+\\.js\\?ver=([\\d.]+)$\\;version:\\1"`. This was taken from [technologies/e.json](https://github.com/wappalyzer/wappalyzer/blob/master/src/technologies/e.json).
But, in the HTML, there's also the script that has the source `hello-elementor/assets/js/hello-frontend.min.js?ver=1.0.0"`. So, wappalyzer mathces the first occurrence and sets the version to 1.0.0, instead of the correct one.

**Additional problems**
Given this website: https://www.artacademybrand.it/en/ , wappalyzer only detects Elementor but not its version.

**Possible solutions**
- Add a better regex for `js` that identifies the version. The one that I found is `window.elementorFrontendConfig.version`, that gives the exact version.
- Make a better regex for `scriptSrc` that excludes the `hellow-elementor` script

The first solution works for both the example websites that I gave. The second solution works only for the first one.

I expect wappalyzer to be agnostic of static information, such as filenames, as much as possible. And I think that making decisions based on looking at the javascript runtime is better overall.

I would like to add the following in the `js` section of `Elementor`, at [e.json](https://github.com/wappalyzer/wappalyzer/blob/master/src/technologies/e.json):
```
"window.elementorFrontendConfig.version": "^(.+)$\\;version:\\1"
```
And expect it to solve this bug and any bugs regarding the filename of the javascript, for Elementor.

**Comment by AliasIO** [comment]
Thanks for the report!
