### ISSUE TITLE
Webflow technology icon not properly sized

### ISSUE THREAD

**Issue by seirdotexe** [wappalyzer/wappalyzer#7117]
**Platform**
Which platform does the bug apply to?
* WebExtension (Mozilla Firefox) Version 6.10.50

**Describe the bug**
The technology icon of Webflow isn't sized properly as shown below.
![image](https://user-images.githubusercontent.com/80536518/204158740-d1b760af-98f2-4d93-a816-461deee72ea4.png)

**To Reproduce**
1. Enable setting **Use technology icon instead of Wappalyzer logo**
2. Go to [useblackbox.io](useblackbox.io)
3. Notice incorrect technology icon sizing

**Expected behavior**
The technology icon should size properly.

**Comment by AliasIO** [comment]
Thanks!
