### ISSUE TITLE
Track 'Clutch'

### ISSUE THREAD

**Issue by John4266** [wappalyzer/wappalyzer#7203]
Vendor Site - https://clutch.co/
Category - Reviews, Widgets
Example Sites:
https://bluesoft.com/
https://www.xfive.co/
Detections:
1. `iframe` tag with `src`: `https://widget.clutch.co/widgets/get/*`
2. `script` tag with `src`: `https://widget.clutch.co/static/js/widget.js`

**Comment by dhavalveera** [comment]
@John4266 - please close the Issue, as the Clutch Trace has been added & it'll be released in the new update. Thanks
