### ISSUE TITLE
Vite + Vue is not recognized

### ISSUE THREAD

**Issue by LoryPelli** [wappalyzer/wappalyzer#7218]
My project has the file vite.config.js so I think it's using vite, but why with the extension is not recognized?

**Comment by LoryPelli** [comment]
Also when I created the project it said you successfully created a vite + vue project so I'm pretty sure I'm using vite

**Comment by dhavalveera** [comment]
@LoryPelli can you share the example or project link to check & verify?

**Comment by LoryPelli** [comment]
https://texteditoronline.pages.dev

**Comment by LoryPelli** [comment]
idk if the issue is because I didn't upload the vite config file

**Comment by LoryPelli** [comment]
but also if I run it locally with every file, same issue

**Comment by LoryPelli** [comment]
![image](https://user-images.githubusercontent.com/87276663/208291523-29d50ecd-6ffd-4676-b9c3-4a4f11c0952f.png)

**Comment by LoryPelli** [comment]
Also wappalyzer said my site had corejs, sometimes it says this and sometimes not, so idk...

**Comment by dhavalveera** [comment]
@LoryPelli - currently detection of `Vitejs` seems to be difficult, as need more time on it to identify the proper trace for `Vitejs`. @nurbek91

**Comment by dhavalveera** [comment]
> Also wappalyzer said my site had corejs, sometimes it says this and sometimes not, so idk...

in which website, corejs is beein detected sometimes & sometimes doesn't? can you share examples for it too?

**Comment by LoryPelli** [comment]
> > Also wappalyzer said my site had corejs, sometimes it says this and sometimes not, so idk...
> 
> in which website, corejs is beein detected sometimes & sometimes doesn't? can you share examples for it too?

Same website
https://texteditoronline.pages.dev

**Comment by LoryPelli** [comment]
What about corejs thing?

**Comment by dhavalveera** [comment]
> What about corejs thing?

I just checked again, and it's not detecting the `core-js`

**Comment by LoryPelli** [comment]
> > What about corejs thing?
> 
> 
> 
> I just checked again, and it's not detecting the `core-js`

It was, should it?

**Comment by LoryPelli** [comment]
> > > What about corejs thing?
> > 
> > 
> > I just checked again, and it's not detecting the `core-js`
> 
> It was, should it?

@dhavalveera 
![image](https://user-images.githubusercontent.com/87276663/208469919-80174966-276f-43c5-b0b5-4aaa29567290.png)

**Comment by LoryPelli** [comment]
After the latest re-build to update vite version, the extension is able to identify corejs, but you should find a way to fix this, because I think that with another build, it will get broken again

**Comment by dhavalveera** [comment]
also @LoryPelli - for this `core-js`, can you please create a new separate issue for it>

**Comment by LoryPelli** [comment]
> @LoryPelli - currently detection of `Vitejs` seems to be difficult, as need more time on it to identify the proper trace for `Vitejs`. @nurbek91

Any updates?
