### ISSUE TITLE
CLI does not finish when return TypeError Invalid URL

### ISSUE THREAD

**Issue by kaloomte** [wappalyzer/wappalyzer#7228]
**Platform**
* node v19.2.0
* wappalyzer 6.10.47
* OS Debian GNU/Linux 11

**Describe the bug**
When i give invalid url for scan with CLI scan does not finish. I have to press Ctrl+C for close. I expected finish the command even error occurs. I'm not familiar with node sorry for if i miss something about it.

**To Reproduce**
`$ wappalyzer github.com`

```
Error: TypeError [ERR_INVALID_URL]: Invalid URL
    at new Site (/root/.nvm/versions/node/v19.2.0/lib/node_modules/wappalyzer/driver.js:438:13)
    at Driver.open (/root/.nvm/versions/node/v19.2.0/lib/node_modules/wappalyzer/driver.js:409:12)
    at /root/.nvm/versions/node/v19.2.0/lib/node_modules/wappalyzer/cli.js:115:35
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

![wappalyzer-error](https://user-images.githubusercontent.com/42833660/208664969-612268e3-070b-4336-a015-58cba6de2e7d.png)

**Comment by dhavalveera** [comment]
@kaloomte  - if due to some error if the app is crashed, the reference you shared, it'll not execute the next line as the app has crashed and this way nodejs works

**Comment by AliasIO** [comment]
It looks like closing the browser can sometimes cause the script to hang, I added a 3 second timeout in 7b5b5b3db3ea26397fa74f952aa1ee9ca9696ebe. I also added a validation step so the browser doesn't get started when the URL is invalid.
