### ISSUE TITLE
Lookup on the website

### ISSUE THREAD

**Issue by LoryPelli** [wappalyzer/wappalyzer#7235]
If I use lookup on the wappalyzer website, it shows old technologies for https://texteditoronline.pages.dev

**Comment by dhavalveera** [comment]
which old technologies? @LoryPelli

**Comment by LoryPelli** [comment]
> which old technologies? @LoryPelli

My website doesn't use anymore cloudflare browser isight but it get detected by wappalyzer website (not extension) also it's using vue which isn't detected by website also if it should...

**Comment by dhavalveera** [comment]
> > which old technologies? @LoryPelli
> 
> My website doesn't use anymore cloudflare browser insights but it get detected by wappalyzer website (not extension) also it's using vue which isn't detected by website also if it should...

you're referring about Wappalyzer's Official Website, not Browser Extension?

**Comment by dhavalveera** [comment]
I'm not sure about the website

**Comment by AliasIO** [comment]
The lookup results on the website are cached and will update automatically after some time.

**Comment by LoryPelli** [comment]
> The lookup results on the website are cached and will update automatically after some time.

How much time?
