### ISSUE TITLE
Technologies Issue

### ISSUE THREAD

**Issue by LoryPelli** [wappalyzer/wappalyzer#7252]
Try to host a website for example on 127.0.0.1, then check technologies on wappalyzer, then host another website with completely different technologies, for me it will continue to say old technologies and I need to reinstall the extension.

**Comment by dhavalveera** [comment]
the same thing happens to me when running `127.0.0.1` or `localhost`, it might be due to cache or something, not sure @LoryPelli

**Comment by LoryPelli** [comment]
> the same thing happens to me when running `127.0.0.1` or `localhost`, it might be due to cache or something, not sure @LoryPelli

Is there a way to fix this? I mean by adding something in the extension code?

**Comment by dhavalveera** [comment]
@AliasIO & @nurbek91  - can help more on this, have to identify this what can be done

**Comment by AliasIO** [comment]
You can go into the extension settings and click 'clear cached detections'. There's also a setting to turn cached detections off completely. By default the extension will remember what it sees on a given hostname or IP address for a day or so.
