### ISSUE TITLE
ElementUI detection

### ISSUE THREAD

**Issue by LoryPelli** [wappalyzer/wappalyzer#7258]
The website https://texteditoronline.pages.dev it's using it but the extension takes too much time to identify it, idk if this can be fixed in some ways...

**Comment by dhavalveera** [comment]
Hey @LoryPelli I Inspected the HTML Code through which the `Element UI` is being detected, but in your code, I didn't find any trace which can detect `Element UI`

**Comment by LoryPelli** [comment]
> Hey @LoryPelli I Inspected the HTML Code through which the `Element UI` is being detected, but in your code, I didn't find any trace which can detect `Element UI`

You need to click on the button save for example

**Comment by LoryPelli** [comment]
I will close this because I'm now using buttons from library, so now it's detected correctly
