### ISSUE TITLE
No option to pass local storage/session storage

### ISSUE THREAD

**Issue by darshanpjpt** [wappalyzer/wappalyzer#7268]
In the CLI version, There is an option to pass the headers, which can help in performing authenticated technology detection on PHP, and .Net web apps. we can supply cookies with a header flag and the wappalyzer will run as an authenticated user.

But in the case of single-page applications (SPAs), supplying a cookie header merely is not enough for authentication. They require session and local storage set in the browser to decide if the state is authenticated.

![Screenshot from 2022-12-31 12-40-17](https://user-images.githubusercontent.com/71147956/210128584-0c3b4717-e41a-4977-a4d3-12d78df88c90.png)

Hence, In the case of no session storage and local storage set, the Wappalyzer will always run as unauthenticated on the SPAs.

**Comment by AliasIO** [comment]
Added in f4fc3e66a6b52c0577b5d99de6ebc18faeba8bae.

You can pass a JSON string, e.g. `--session-storage='{ "userName": "Demo User", "email": "test@test.com" }'`.
