### ISSUE TITLE
[Suggestion] technology "oss" property improvement

### ISSUE THREAD

**Issue by ysm-dev** [wappalyzer/wappalyzer#7278]
If the `oss` property of the technology is improved to the open source repository URL (`string` type) of the technology instead of the `boolean` type, 

It will be more informative.

I can contribute on this.

**Comment by AliasIO** [comment]
I think it would be better to add a `repoUrl` and maybe a `license` field but I'm not sure if there's much benefit maintaining this information,

**Comment by dhavalveera** [comment]
also, @ysm-dev = if we add OSS Repository URL, and when we open the browser extension & click on the OSS Technology, then at that place we're showing the either the OSS Official Page or GitHub Repo, if I'm not wrong @AliasIO
