### ISSUE TITLE
hide Nextjs from wappalyzer

### ISSUE THREAD

**Issue by jsina** [wappalyzer/wappalyzer#7282]
Hello there
I wanna know how to hide nextjs project from wappalyzer.
I've already disabled `poweredByHeader: false,` in `next.config` file but it wouldn't work.
tnx

**Comment by dhavalveera** [comment]
we're not only detecting the `Nextjs` from Headers only, there're other things as well which is used to trace the Nextjs

**Comment by AliasIO** [comment]
See https://github.com/wappalyzer/wappalyzer/blob/master/src/technologies/n.json#L559.

**Comment by jsina** [comment]
you know, I need to hide all front-end information from wappalyzer. but I don't find any document related to.

**Comment by jsina** [comment]
@AliasIO can u explain more about the link.

**Comment by AliasIO** [comment]
@jsina We look for the `x-powered-by` header but also the `__NEXT_DATA__` and `next` JavaScript variables on the page. We also detect Next.js when other technologies are detected that are know to use Next.js.

There isn't much point trying to hide it though, see https://www.wappalyzer.com/articles/how-to-hide-technologies-from-wappalyzer/.

**Comment by jsina** [comment]
thanks a lot @AliasIO
