### ISSUE TITLE
Stripe not detected in CLI but shows in Chrome Extension

### ISSUE THREAD

**Issue by cantonalex** [wappalyzer/wappalyzer#7294]
**Platform**
Which platform does the bug apply to?
Chrome 
https://explodingtopics.com/checkout-pro-entrepreneur

**Describe the bug**
Stripe not detected. But can see it in frontend source code 

**To Reproduce**
Inspect element, CMD + F stripe 

**Expected behavior**
Stripe detected

**Additional context**

**Comment by dhavalveera** [comment]
@cantonalex => I just checked the website you shared, and I'm able to see the Stripe in the Wappalyzer Extension.

**Comment by cantonalex** [comment]
Surely there was a bugfix cause that sure as heck wasn't there a few days ago haha

**Comment by cantonalex** [comment]
@dhavalveera here is another example of a site with stripe in source code but not showing on wapalyzer https://app.trendrocket.io

**Comment by cantonalex** [comment]
I was right. In the CLI it doesn't show stripe

**Comment by cantonalex** [comment]
`{"urls":{"https://explodingtopics.com/":{"status":200}},"technologies":[{"slug":"algolia","name":"Algolia","description":"Algolia offers a hosted web search product delivering real-time results.","confidence":100,"version":null,"icon":"Algolia.svg","website":"http://www.algolia.com","cpe":null,"categories":[{"id":29,"slug":"search-engines","name":"Search engines"}],"rootPath":true},{"slug":"node-js","name":"Node.js","description":"Node.js is an open-source, cross-platform, JavaScript runtime environment that executes JavaScript code outside a web browser.","confidence":100,"version":null,"icon":"Node.js.svg","website":"http://nodejs.org","cpe":"cpe:2.3:a:nodejs:node.js:*:*:*:*:*:*:*:*","categories":[{"id":27,"slug":"programming-languages","name":"Programming languages"}]},{"slug":"chart-js","name":"Chart.js","description":"Chart.js is an open-source JavaScript library that allows you to draw different types of charts by using the HTML5 canvas element.","confidence":50,"version":null,"icon":"Chart.js.svg","website":"https://www.chartjs.org","cpe":null,"categories":[{"id":25,"slug":"javascript-graphics","name":"JavaScript graphics"}],"rootPath":true},{"slug":"react","name":"React","description":"React is an open-source JavaScript library for building user interfaces or UI components.","confidence":100,"version":null,"icon":"React.svg","website":"https://reactjs.org","cpe":"cpe:2.3:a:facebook:react:*:*:*:*:*:*:*:*","categories":[{"id":12,"slug":"javascript-frameworks","name":"JavaScript frameworks"}],"rootPath":true},{"slug":"next-js","name":"Next.js","description":"Next.js is a React framework for developing single page Javascript applications.","confidence":100,"version":"7.0.2","icon":"Next.js.svg","website":"https://nextjs.org","cpe":"cpe:2.3:a:zeit:next.js:*:*:*:*:*:*:*:*","categories":[{"id":18,"slug":"web-frameworks","name":"Web frameworks"},{"id":22,"slug":"web-servers","name":"Web servers"}],"rootPath":true},{"slug":"polyfill","name":"Polyfill","description":"Polyfill is a service which accepts a request for a set of browser features and returns only the polyfills that are needed by the requesting browser.","confidence":100,"version":"2","icon":"polyfill.svg","website":"https://polyfill.io","cpe":null,"categories":[{"id":59,"slug":"javascript-libraries","name":"JavaScript libraries"}],"rootPath":true},{"slug":"google-tag-manager","name":"Google Tag Manager","description":"Google Tag Manager is a tag management system (TMS) that allows you to quickly and easily update measurement codes and related code fragments collectively known as tags on your website or mobile app.","confidence":100,"version":null,"icon":"Google Tag Manager.svg","website":"http://www.google.com/tagmanager","cpe":null,"categories":[{"id":42,"slug":"tag-managers","name":"Tag managers"}],"rootPath":true},{"slug":"twitter-ads","name":"Twitter Ads","description":"Twitter Ads is an advertising platform for Twitter 'microblogging' system.","confidence":100,"version":null,"icon":"Twitter.svg","website":"https://ads.twitter.com","cpe":null,"categories":[{"id":36,"slug":"advertising","name":"Advertising"}],"rootPath":true},{"slug":"profitwell","name":"Profitwell","description":null,"confidence":100,"version":null,"icon":"Profitwell.svg","website":"https://www.profitwell.com/","cpe":null,"categories":[{"id":10,"slug":"analytics","name":"Analytics"}],"rootPath":true},{"slug":"optinmonster","name":"OptinMonster","description":"OptinMonster is a conversion optimisation tool that allows you to grow your email list.","confidence":100,"version":null,"icon":"OptinMonster.png","website":"https://optinmonster.com","cpe":null,"categories":[{"id":32,"slug":"marketing-automation","name":"Marketing automation"}],"rootPath":true},{"slug":"google-analytics","name":"Google Analytics","description":"Google Analytics is a free web analytics service that tracks and reports website traffic.","confidence":100,"version":null,"icon":"Google Analytics.svg","website":"http://google.com/analytics","cpe":null,"categories":[{"id":10,"slug":"analytics","name":"Analytics"}],"rootPath":true},{"slug":"core-js","name":"core-js","description":"core-js is a modular standard library for JavaScript, with polyfills for cutting-edge ECMAScript features.","confidence":100,"version":"2.6.12","icon":"core-js.png","website":"https://github.com/zloirock/core-js","cpe":null,"categories":[{"id":59,"slug":"javascript-libraries","name":"JavaScript libraries"}],"rootPath":true},{"slug":"google-font-api","name":"Google Font API","description":"Google Font API is a web service that supports open-source font files that can be used on your web designs.","confidence":100,"version":null,"icon":"Google Font API.svg","website":"http://google.com/fonts","cpe":null,"categories":[{"id":17,"slug":"font-scripts","name":"Font scripts"}],"rootPath":true},{"slug":"recaptcha","name":"reCAPTCHA","description":"reCAPTCHA is a free service from Google that helps protect websites from spam and abuse.","confidence":100,"version":null,"icon":"reCAPTCHA.svg","website":"https://www.google.com/recaptcha/","cpe":null,"categories":[{"id":16,"slug":"security","name":"Security"}]},{"slug":"cloudflare","name":"Cloudflare","description":"Cloudflare is a web-infrastructure and website-security company, providing content-delivery-network services, DDoS mitigation, Internet security, and distributed domain-name-server services.","confidence":100,"version":null,"icon":"CloudFlare.svg","website":"http://www.cloudflare.com","cpe":null,"categories":[{"id":31,"slug":"cdn","name":"CDN"}],"rootPath":true},{"slug":"webpack","name":"Webpack","description":"Webpack is an open-source JavaScript module bundler.","confidence":100,"version":null,"icon":"Webpack.svg","website":"https://webpack.js.org/","cpe":null,"categories":[{"id":19,"slug":"miscellaneous","name":"Miscellaneous"}],"rootPath":true},{"slug":"babel","name":"Babel","description":"Babel is a free and open-source transcompiler for writing next generation JavaScript.","confidence":100,"version":null,"icon":"Babel.svg","website":"https://babeljs.io","cpe":null,"categories":[{"id":19,"slug":"miscellaneous","name":"Miscellaneous"}],"rootPath":true},{"slug":"open-graph","name":"Open Graph","description":"Open Graph is a protocol that is used to integrate any web page into the social graph.","confidence":100,"version":null,"icon":"Open Graph.png","website":"https://ogp.me","cpe":null,"categories":[{"id":19,"slug":"miscellaneous","name":"Miscellaneous"}],"rootPath":true},{"slug":"module-federation","name":"Module Federation","description":"Module Federation is a webpack technology for dynamically loading parts of other independently deployed builds.","confidence":50,"version":null,"icon":"Webpack.svg","website":"https://webpack.js.org/concepts/module-federation/","cpe":null,"categories":[{"id":19,"slug":"miscellaneous","name":"Miscellaneous"}]},{"slug":"http-3","name":"HTTP/3","description":"HTTP/3 is the third major version of the Hypertext Transfer Protocol used to exchange information on the World Wide Web.","confidence":100,"version":null,"icon":"HTTP3.svg","website":"https://httpwg.org/","cpe":null,"categories":[{"id":19,"slug":"miscellaneous","name":"Miscellaneous"}],"rootPath":true}]}`

**Comment by cantonalex** [comment]
Would love better stripe detection. These are all examples of sites with stripe. 
https://photoai.com/
https://sublaunch.co/

**Comment by AliasIO** [comment]
The CLI detects Stripe on the first URL you shared (https://explodingtopics.com/checkout-pro-entrepreneur) but not on the others. I had a look at the source code and there are no links to billing.stripe.com, it looks like the button click and redirect is done in JavaScript somewhere. I did see a `stripeLoaded` JS variable on https://photoai.com but this seems to be non-standard and isn't used on other sites. I'm not seeing a way to improve the detection here.

**Comment by cantonalex** [comment]
another site https://app.convertkit.com/users/signup?plan=300-annual 
`https://js.stripe.com/v3/` detected in the network headers

**Comment by cantonalex** [comment]
another site with `billing.stripe.com` but not detected https://www.movevirtual.co/

**Comment by AliasIO** [comment]
I'll add in detection for links to 'billing.stripe.com' that open in a new tab.

**Comment by cantonalex** [comment]
that would be awesome could you also do requests to `https://js.stripe.com/v2/` eg https://cartpops.com/pricing/
