### ISSUE TITLE
Technologies Database Letter `p` is not JSON

### ISSUE THREAD

**Issue by rdzsp** [wappalyzer/wappalyzer#7301]
**Platform**
Which platform does the bug apply to?
Technologies Database

**Describe the bug**
This json file can't be parsed to json,
https://raw.githubusercontent.com/wappalyzer/wappalyzer/master/src/technologies/p.json

**To Reproduce**
1. Install json formatter addons for browser.
2. Go to 'https://raw.githubusercontent.com/wappalyzer/wappalyzer/master/src/technologies/p.json'.
3. The parser can't parsing this page to json, so there is missing character ruins the JSON format.

**Expected behavior**
The file is valid JSON.

**Comment by mwullink** [comment]
notices same thing.

The new Partytown sig is missing a comma,  this is causing json validation error.

file: https://github.com/wappalyzer/wappalyzer/blob/0b00e6f037f7dea28295e690d4e7ddcc7868cbe8/src/technologies/p.json
line: 524

"dom": "script[type*='text/partytown']"  <<--  must add comma here
