### ISSUE TITLE
 Track "Angie" Webserver

### ISSUE THREAD

**Issue by libDarkstreet** [wappalyzer/wappalyzer#7321]
Website: https://angie.software/en/
Github: https://github.com/webserver-llc/angie

Detection: Server header containing the word "Angie".

The version number usually appears in the server header like this: "Angie/1.0.0"

![image](https://user-images.githubusercontent.com/55440418/212323364-422f77d2-0e8e-42c6-893e-e443983a8e29.png)

**Comment by AliasIO** [comment]
Added, thanks!
