### ISSUE TITLE
Next.js should have the same Categories as Nuxt.is

### ISSUE THREAD

**Issue by gilbertococchi** [wappalyzer/wappalyzer#7333]
Next.js currently is categorized only on 18 (Web Frameworks) and 22 (Web Server) https://github.com/wappalyzer/wappalyzer/blob/master/src/technologies/n.json#L593

While Nuxt.js is also categorized on 12 (Javascript Frameworks).

Is there a good reason why Next.js is not categorized also as Javascript Framework?

@housseindjirdeh FYI

**Comment by rviscomi** [comment]
+1 this seems like a good change for consistency

**Comment by AliasIO** [comment]
Updated in 4f56076808acc9de0966ca234743816a122e4b6b 👍
