### ISSUE TITLE
Angie webserver detection does not work if the version number is not present.

### ISSUE THREAD

**Issue by libDarkstreet** [wappalyzer/wappalyzer#7352]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome, Mozilla Firefox)

I haven't tried elsewhere but I guess it's a regex bug.

**Describe the bug**
Angie webserver detection does not work if the version number is not present.

If the header content is "Angie/1.0.0" then the detection works, if it's just "Angie" then it doesn't.

**Comment by dhavalveera** [comment]
can you share the website examples where you've encountered this problem?

**Comment by libDarkstreet** [comment]
I have experienced it on my own blog. In my web server configuration, the server tokens are disabled, so no version number is shown. 

https://bitlords.net

**Comment by dhavalveera** [comment]
I've resolved the detection problem, for you it'll be resolved in next release

**Comment by libDarkstreet** [comment]
Cool, thanks!
