### ISSUE TITLE
NGINX with C issue

### ISSUE THREAD

**Issue by seirdotexe** [wappalyzer/wappalyzer#7361]
Since a few days, every website running NGINX shows that it's using the C programming language. I'm guessing this is a bug?

**Comment by John4266** [comment]
I also don't think websites using tools such as `NGINX` or even `mdBook` should imply the languages they (the tools) were built with
unless its something else such as frameworks/libraries, etc which usually require using specific languages.

**Comment by nurbek91** [comment]
I wouldn't say it's a bug. After all, we have defined the server and it is written in C
Similar situation here:
```
"Caddy": {
    "cats": [
      22
    ],
    "cpe": "cpe:2.3:a:caddyserver:caddy:*:*:*:*:*:*:*:*",
    "headers": {
      "Server": "^Caddy$"
    },
    "icon": "caddy.svg",
    "implies": "Go",
    "website": "http://caddyserver.com"
  },
```
But I removed the line at your request.

**Comment by AliasIO** [comment]
I agree with @John4266, Nginx should not imply C and Caddy should not imply Go. Every website will use C somewhere in the stack but it's not really relevant. The exception would be servers that only work with one specific language or runtime, like Express.js. Updated in aff18efafa0768504118b4a11424555602dcfebe.

**Comment by John4266** [comment]
> I also don't think websites using tools such as `NGINX` or even `mdBook` should imply the languages they (the tools) were built with unless its something else such as frameworks/libraries, etc which usually require using specific languages.

`mdBook` and `SWC` shouldn't imply `Rust` since they are just tools and not frameworks.

**Comment by AliasIO** [comment]
I'll update those too.
