### ISSUE TITLE
Aborted requests via interceptor cause the whole website to stop loading and missing the detections

### ISSUE THREAD

**Issue by RootLUG** [wappalyzer/wappalyzer#7370]
**Platform**
Which platform does the bug apply to?
* NPM

**Describe the bug**
When scanning the website for technologies, I noticed there are checks that may block requests via the puppeteer interceptor (as described here https://pptr.dev/guides/request-interception ), this causes to throw an exception at page.goto location which prevents wappalyzer to collect rest of the data for the purpose of technology detection (if there is for example an iframe on the website)
I would expect that this should not block the whole page from loading (currently the driver just closes the connection/headless browser) or as an additional mechanism when more graceful blocking is possible, rather then blocking, it should filter the data from those requests that are not suitable for wappalyzer technology detection

**To Reproduce**
scan "http://acc-crmauth.lineas.net/" via the npm wappalyzer module which causes request to be aborted missing most of the technologies, example output:
```
{"urls":{"http://acc-crmauth.lineas.net/":{"status":302,"error":"net::ERR_BLOCKED_BY_CLIENT at http://acc-crmauth.lineas.net/ (https://acc-crmauth.lineas.net/)"},"https://acc-crmauth.lineas.net/":{"status":302}},"technologies":[{"slug":"digicert","name":"DigiCert","description":null,"confidence":100,"version":null,"icon":"DigiCert.svg","website":"https://www.digicert.com/","cpe":null,"categories":[{"id":70,"slug":"ssl-tls-certificate-authorities","name":"SSL/TLS certificate authorities"}],"rootPath":true}]}
```

**Expected behavior**
Rest of the website should be allowed to load so the data for technology detection can be fetched and analyzed.

**Comment by AliasIO** [comment]
Looks like it's because it redirects twice. I updated the code to allow for up to three redirects in 024f50531ac745174bf07ba81cfb1769b65f337e.
