### ISSUE TITLE
Change 'CodeMirror' Category

### ISSUE THREAD

**Issue by John4266** [wappalyzer/wappalyzer#7388]
Hi. I am pretty sure we can move [CodeMirror](https://www.wappalyzer.com/technologies/miscellaneous/codemirror/) to `Editors` & `Widgets` (like [CodeSandbox](https://www.wappalyzer.com/technologies/editors/codesandbox/)) or `Rich text editors` (like [Ace](https://www.wappalyzer.com/technologies/rich-text-editors/ace/)), for consistency.

**Comment by AliasIO** [comment]
Thanks 👍
