### ISSUE TITLE
CLI & Function call have less data than Chrome extension

### ISSUE THREAD

**Issue by cantonalex** [wappalyzer/wappalyzer#7389]
All three have varying levels of output with the Chrome extension being the most detailed..

**Comment by cantonalex** [comment]
@AliasIO do you know how I can get the chrome extension output the same as the wappalyzer package?

**Comment by AliasIO** [comment]
Can you share some examples? The code base is the same but there can be some minor differences. The Chrome extension may pick up on asynchronously loaded (i.e. delayed) scripts, whereas the CLI does not. The Chrome extension may also pick up on technologies loaded after you accept a cookie consent prompt. The CLI checks things like DNS records, which the extension does not.

You'll get the most comprehensive results with the CLI by running a recursive crawl. Use can also use the paid [API](https://www.wappalyzer.com/api/), which has the most complete results.

**Comment by cantonalex** [comment]
explodingtopics.com Stripe seems to show every time on Chrome. and very rarely on the CLI

**Comment by cougrimes** [comment]
I'm running into the exact same issue, where the browser extension detects far more than function or CLI. Granted, I'm looking at technologies that primarily are detected via `js`, but I've also struggled to use `scriptSrc` in a way that consistently detects. Given that I intended to use Wappalyzer for bulk site analysis, it's surprising to see that it can't handle this in CLI mode.

**Comment by AliasIO** [comment]
The main difference is that the extension does a second pass to check JavaScript variables on the page after five seconds to catch anything loaded asynchronously. The CLI does a single pass and returns the results as quickly as possible. I could add an option to enable this behaviour in the CLI but then you'd have to wait 5+ seconds to get a response.

**Comment by cougrimes** [comment]
@AliasIO: There's a strong use case for having an option that does that second pass after a full load, as plenty of technologies can't be detected otherwise (e.g., anything loaded by a tag manager). Having such an option would be immensely helpful.

**Comment by AliasIO** [comment]
There's no way to know when everything has fully loaded, I've seen cases where scripts were still being injected after 15 seconds. I could add an option to always wait _n_ seconds after the page has been loaded before analysing, it's just not well suited for scanning large numbers of websites.

**Comment by cougrimes** [comment]
@AliasIO : Oh, agreed that it's a specialized use case—but at least the CLI can be programmatically run through over time and recoded vs. using the browser to achieve the same effect. Any work would be appreciated, as this is just outside the zone of things I'm comfortable doing in a fork.

**Comment by AliasIO** [comment]
Added a `--defer` option in f353a5e6e5bad0a5ac5e4c577c4d18a4e0fcda93. 👍

**Comment by cantonalex** [comment]
Thanks for the addition Alias. I gave it a test, still doesn't seem to make a difference re

> This is all with recursive on

**Comment by cantonalex** [comment]
Did this solve your issue @cougrimes. Didn't seem to fix mine
https://github.com/wappalyzer/wappalyzer/issues/7389#issuecomment-1407302169
