### ISSUE TITLE
Astro 2.0 Detection: Needs Update

### ISSUE THREAD

**Issue by FredKSchott** [wappalyzer/wappalyzer#7411]
[Astro 2.0 recently released](https://astro.build/blog/astro-2/) with an updated scheme for where built/bundled assets are written to. The initial `/_astro/` check is still correct, but the filenames format have changed to be much less rigid than they were in the v0.x days. This is by far the most reliable way to detect an Astro website, so it would be great to get this fixed for reliable data.

Here is the failing check in question:

https://github.com/wappalyzer/wappalyzer/blob/ae1c761b687d1a0fa02b4523bb4500e85f7c7471/src/technologies/a.json#L3892-L3896

And here is an example of all relevant network requests made on https://astro.build/. These all pass the initial `/_astro/` check but none of these pass the regex (note the use of `.` instead of `-`).

<img width="440" alt="Screen Shot 2023-02-07 at 6 51 12 PM" src="https://user-images.githubusercontent.com/622227/217326144-494ccc39-e174-417c-a910-ca2bbe3c3314.png">

Given that `"link[href*='/_astro/']"` should be unique enough to match an Astro website, is it safe to remove the `"attributes": { ... }` key entirely from this check? Or is some other change needed? I'm happy to drive the PR, but want to make sure I understand the change before submitting.

RE backwards compatability: I actually don't think that this check ever passed on Astro v1.x, which would make it 6+ months old. So I would suggest making this change without needing to preserve the previous outdated check. 

_Context: I am a core maintainer of Astro._

**Comment by AliasIO** [comment]
Thanks!
