### ISSUE TITLE
Track 'imunify360'

### ISSUE THREAD

**Issue by John4266** [wappalyzer/wappalyzer#7432]
Vendor Site - https://imunify360.com/
Category - Security
Example Site - https://ipolice.co.il/
Detection:
`server` header
name/version
example: `server: imunify360-webshield/1.18`

**Comment by nurbek91** [comment]
Hey mate, couldn't test it locally, I hope added the technology correctly. Traces look consistently the same
![image](https://user-images.githubusercontent.com/3456008/218825309-37a92d7b-5c99-46b8-8939-80d5d858a8b7.png)

**Comment by John4266** [comment]
> Hey mate, couldn't test it locally

Are you talking about the https://ipolice.co.il/ website?
It should appear on the first request's response headers.
![](https://i.imgur.com/w0GyMeR.png)

**Comment by AliasIO** [comment]
Thanks!
