### ISSUE TITLE
How Wappalyzer identifies the technologies of a site?

### ISSUE THREAD

**Issue by micilini** [wappalyzer/wappalyzer#7438]
Currently I believe there are two different ways to validate the technologies of a website:

1) Through the HTML content (it seems that Wappalyzer analyzes the HTML code in search of certain Tags, and when found, it judges that that page has that technology).

2) Through the header Head tags (where Wappalyzer validates each parameter in search of a technology)

I would like to know if this is how Wappalyzer works, if not, what other way can it get the technology of a certain site?

**Comment by AliasIO** [comment]
You can read more about how Wappalyzer works in the REAME:

https://github.com/wappalyzer/wappalyzer#specification

There's lot more we look at including JavaScript variables, cookies, response headers, SSL certificates, etc.
