### ISSUE TITLE
Add IPs as a factor in determining the network a website is using

### ISSUE THREAD

**Issue by nikolqy** [wappalyzer/wappalyzer#7441]
I wasn't able to find an issue similar to this one, so sorry if it's a repeat.

I think it would be really helpful to determine a websites network provider based on the ip address of the website.

Possible issues that could prevent this from being accurate:
If a website is using multiple CDNs, it might be inaccurate, but I'm not sure if Wappalyzer is going for accuracy rather than what is given, which should be assumed to be accurate (like a webserver version)

This could also mislead people and confuse people. For example, Digital Ocean is more than likely hosted at Digital Ocean, but their website itself is delivered by Cloudflare. I'm not sure if this would be a problem that might confuse users, but I'm going to assume that if someone is using Wappalyzer, they're more than likely aware of how the web works anyways and it wouldn't mislead them

There's also the problem of network ownership and 3rd parties buying a part of a network or  entire networks. For example: google selling a range of ips to a SaaS company to use like Netlify, or Edgio acquiring Edgecast, Layer0 and Limelight. 

Perks:
Accuracy of deterring what network delivered a site should be very accurate and easy to maintain.

I say if this is done, it should actually be added as a feature that tells you the network that delivered the website rather than trying to determine the company that might own the ip range and what not.

Almost all providers have a very accessible ip range list for their services
For example:
https://www.cloudflare.com/ips/
https://cachefly.cachefly.net/ips/cdn.txt & https://cachefly.cachefly.net/ips/rproxy.txt

I'm not sure if this is possible with a plugin, but I'm assuming that if the plugin can read headers, it can read ips.

Would love to know what your thoughts are!

**Comment by AliasIO** [comment]
Would be good but I don't think there's a way to get the website's IP address in the WebExtension.

**Comment by nikolqy** [comment]
Wow, that is very interesting. I wondered if that might be the reason it wasn't already a feature. The only way around this appears to be using an external source of information, like a DNS api, which could have some inaccuracy issues depending on origin location etc., but it is a thought.

Google seems to have a json dns api https://dns.google/resolve?name=github.com
Cloudflare does as well, but I do not think it takes url requests like Google does. I also think Cloudflare's api requires an external script for decoding the dns response.
