### ISSUE TITLE
Fewer technologies displayed than indicated by the icon on the extension

### ISSUE THREAD

**Issue by olekstomek** [wappalyzer/wappalyzer#7451]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome, Mozilla Firefox)

**Describe the bug**
Randomly when I click on the wappalyzer icon I see that less technologies used on a given website are shown than the extension counter shows. Random websites.
Take a look, on top right counter I see number 12 but in technologies you can see only 6 technologies:
![wappalyzer](https://user-images.githubusercontent.com/26818304/219750919-3d7274a9-a885-4e40-a853-1df264b8c0ea.png)
I click again on extension and next technologies are added:
![wappalyzer2](https://user-images.githubusercontent.com/26818304/219751172-886cad9e-3853-4073-aa16-de3b6d4755c5.png)

**To Reproduce**
1. Go to random website
2. Click on icon of extension to check used technologies for opened page
3. Randomly you can see less listed technologies than number on icon of extension.

**Expected behavior**
I see correct number od technologies according to number on icon of extension. 

**Additional context**
It is not often.

**Comment by olekstomek** [comment]
One more case:
![image](https://user-images.githubusercontent.com/26818304/220379936-5f543057-7c57-42d3-ab25-0e9cdc242281.png)

I see that "no technologies detected" but on icon of extension I see number 12.

**Comment by AliasIO** [comment]
Does the number update while you have the pop-up open? The pop-up doesn't update while it's open.

**Comment by olekstomek** [comment]
Yes, the number is updating when I have pop-up opened. So the is no way to have actual information in pop-up without reopen action pop-up (for update)?

**Comment by AliasIO** [comment]
The data is fetched and then rendered when the popup opens so that would be the reason. There may be a way to change that but I'm not sure if it's really worth doing.

**Comment by olekstomek** [comment]
Okay, I'm closing this issue.
