### ISSUE TITLE
Track 'Comeet'

### ISSUE THREAD

**Issue by John4266** [wappalyzer/wappalyzer#7459]
Vendor Site - https://www.comeet.com
Category - Widgets, Form builders (?)
Example Sites:
https://www.onezerobank.com/career/position/?positionID=DB.C15
https://www.comeet.com/jobs/appnext/42.003/mobile-user-acquisition-manager--brazil/BD.63B
Detection:
1. global javascript function `comeetInit()`
2. `script` tag with id `comeet-jsapi`

**Comment by AliasIO** [comment]
Thanks!
