### ISSUE TITLE
Option to return "page source" with CLI

### ISSUE THREAD

**Issue by dan-processbolt** [wappalyzer/wappalyzer#7473]
In the CLI, it would be very handy to have the option to return the page source in the results. This way the page could be saved for further analysis, storage, or debugging.

In this case, by "page source", I am referring to the equivalent of what you would see in a browser when you selected "View page source".

It would be very nice to have when investigating, working on, and debugging technology detection.

Ideally, usage would look something like this:
`console >  node cli.js --page-source https://www.example.com
`

And then the output would look something like this:
`{"urls":{"https://www.example.com/":{"status":200}},"technologies":
...
"page-source":"<!DOCTYPE html>...</html>" }
`

If embedding all that HTML within the return object would be problematic, then encoding the page source in Base64 encoding (or similar) would be just fine too, so then the output would look more like:
`{"urls":{"https://www.example.com/":{"status":200}},"technologies":
...
"page-source":"PCFET0NUWVBFIGh0bWw+Li4uPC9odG1sPg==" }
`

**Comment by AliasIO** [comment]
You can create a copy of cli.js and add a listener to get access to the browser page and access the HTML:

```javascript
const site = await wappalyzer.open(url, headers, storage)

site.on('response', async ({ page }) => {
  const html = await page.content()
})
```
