### ISSUE TITLE
Suppress BeautifulSoup Warnings

### ISSUE THREAD

**Issue by TheTechromancer** [wappalyzer/wappalyzer#7592]
This warning fires occasionally. 

`/Wappalyzer/Wappalyzer.py:58: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.  self.parsed_html = soup = BeautifulSoup(self.html, 'lxml')`

It would be nice to suppress these kinds of BeautifulSoup warnings:
~~~python
import warnings
from bs4 import UserWarning
warnings.filterwarnings("ignore", category=UserWarning, module='bs4')
~~~

Thanks!

**Comment by AliasIO** [comment]
You're in the wrong repo, we don't have any Python code.
