### ISSUE TITLE
DOM checks not used with wappalyzyer-core?

### ISSUE THREAD

**Issue by eaton** [wappalyzer/wappalyzer#7598]
**Platform**
NPM

**Describe the bug**
When using the Wappalyzer Core package in a custom node.js project, 'dom' detectors are skipped.

**To Reproduce**
Load Wappalyzer's technologies, populate the `html` input property with a page's source, and pass it into the Wappalyzer `analyze` function. Although DOM detectors are loaded in the `setTechnologies` function, it's never referenced anywhere else in the codebase.

I'm wiring the Wappalyzer library to a Playwright-based crawler script to gather information for a client about their site. (I'd use the Wappalyzer CLI, but there's quite a bit of other data being gathered along the way, with custom logic for dealing with assorted page types.)

It looks like the cli driver for node.js explicitly handles DOM traversal and testing, while the wappalyzyer-core project ignores it. Would it make more sense to build custom logic mirroring the CLI, working straight from the technology definitions, than using the -core library?

**Comment by AliasIO** [comment]
The `dom` and `js` patterns are handled by the drivers as it requires a browser environment. The way the DOM is accessed depends on the client (e.g. Chrome or Puppeteer). wappalyzer-core can only do static analysis.

https://github.com/wappalyzer/wappalyzer/blob/master/src/drivers/npm/driver.js#L118
https://github.com/wappalyzer/wappalyzer/blob/master/src/drivers/webextension/js/content.js#L44

https://github.com/wappalyzer/wappalyzer/blob/master/src/drivers/npm/driver.js#L59
https://github.com/wappalyzer/wappalyzer/blob/master/src/drivers/webextension/js/content.js#L36

You'd need to replicate these in your own driver. You can still use wappalyzer-core for everything else.

If you require any specific features in the CLI, you're welcome to suggest those too. Perhaps we can make some of the custom logic configurable.

**Comment by AliasIO** [comment]
If you want to create a Playwright driver I'd start by duplicating the [NPM driver ](https://github.com/wappalyzer/wappalyzer/tree/master/src/drivers/npm) and replace any Puppeteer specific logic.
