### ISSUE TITLE
Adding technologies policy

### ISSUE THREAD

**Issue by pieterhartel** [wappalyzer/wappalyzer#7625]
What is your policy on adding technologies to the system?

I have found two technologies that I think would be useful additions. these are:

[swipebox](https://brutaldesign.github.io/swipebox/)
[ddsmoothmenu](http://www.dynamicdrive.com/dynamicindex1/ddsmoothmenu.htm)

I have checked on GitHub that these technologies are not yet implemented: [d](https://github.com/wappalyzer/wappalyzer/blob/master/src/technologies/d.json), [s](https://github.com/wappalyzer/wappalyzer/blob/master/src/technologies/s.json)

**Comment by AliasIO** [comment]
See [here](https://github.com/wappalyzer/wappalyzer/blob/master/CONTRIBUTING.md#adding-a-new-technology). It's not specifically mentioned but we generally don't add single-function libraries or jQuery plugins.

**Comment by pieterhartel** [comment]
Thanks for your quick reply. Perhaps it's useful to mention the policy on the contributing page?
