### ISSUE TITLE
Intercom is not recognized in https://www.wonderpush.com/

### ISSUE THREAD

**Issue by vibl** [wappalyzer/wappalyzer#7635]
**Platform**
* WebExtension (Google Chrome, Mozilla Firefox)

**Describe the bug**
Intercom is not recognized in https://www.wonderpush.com/

**Comment by nurbek91** [comment]
Hey @vibl Everything seems to be working
![image](https://github.com/wappalyzer/wappalyzer/assets/3456008/6912482a-1359-4648-b0f5-a057cc736f3b)
