### ISSUE TITLE
how we can eliminate the unwanted fields from wappalyzer's response - if that will help us improve its response time

### ISSUE THREAD

**Issue by kala15** [wappalyzer/wappalyzer#7640]
is there a option to eliminate as part of technologies array of wappalayzer as it is not required.
description,confidence,version,icon,website,cpe

**Comment by kala15** [comment]
added piece of output for more clarification
```
"technologies": [
    {
      "slug": "varnish",
      "name": "Varnish",
      "description": "Varnish is a reverse caching proxy.",
      "confidence": 100,
      "version": null,
      "icon": "Varnish.svg",
      "website": "http://www.varnish-cache.org",
      "cpe": "cpe:2.3:a:varnish-software:varnich_cache:*:*:*:*:*:*:*:*",
      "categories": [
        {
          "id": 23,
          "slug": "caching",
          "name": "Caching"
        }
      ]
    },
]
```
expected:
"technologies": [
    {
      "slug": "varnish",
      "name": "Varnish",
      "version": null,
      "categories": [
        {
          "id": 23,
          "slug": "caching",
          "name": "Caching"
        }
      ]
    },
]

**Comment by AliasIO** [comment]
There's no option to remove those from the results. It wouldn't make a difference to the response time.

**Comment by kala15** [comment]
Thanks for confirmation
