### ISSUE TITLE
element-plus

### ISSUE THREAD

**Issue by lorypelli** [wappalyzer/wappalyzer#7652]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome)

**Describe the bug**
It was recognized with @import on css but when I linked it to the html as stylesheet and removed @import in css, it doesn't get recognized anymore

**To Reproduce**
1. Go to my website (https://texteditoronline.pages.dev)
2. Click on a button to check that I'm using it
4. It doesn't show in the extension

**Expected behavior**
It should be recognized

**Comment by nurbek91** [comment]
Hey @lorypelli element-plus I do not see a previously added technology with the same name, what do you mean?

**Comment by lorypelli** [comment]
@nurbek91 
![image](https://github.com/wappalyzer/wappalyzer/assets/87276663/0f59082a-586d-4b65-886b-29045cae9661)

**Comment by lorypelli** [comment]
It also should be listed as javascript framework because it is actually a library with styled components...

**Comment by nurbek91** [comment]
Changed category and added other parameters

**Comment by lorypelli** [comment]
> Changed category and added other parameters

Did this fix the issue?
