### ISSUE TITLE
Backdrop CMS detected as both Drupal and Backdrop (again)

### ISSUE THREAD

**Issue by klonos** [wappalyzer/wappalyzer#7654]
I have started noticing this again recently:
![image](https://user-images.githubusercontent.com/2423362/235661324-f0e7b2b9-4cad-4781-b679-44de3bee2529.png)

...and the bad thing is the Drupal gets added as the "main" technology.

I though that we had addressed that in #2841, but obviously not.

Example sites where this is happening:
- https://museum-muri.ch
- https://2bits.com

Example sites where this is NOT happening:
- https://backdropcms.org

I guess this must be because of the mention of the word "drupal" in this line in the rendered HTML output of the page:
```html
<script>window.Backdrop = {settings: {"basePath":"\/","pathPrefix":"","drupalCompatibility":true, ... </script>
```

That `drupalCompatibility` thing is a setting that may be useful during the intial stages of converting a Drupal 7 site to Backdrop CMS, and should be disabled after that, but some site owners forget to do it. See https://github.com/backdrop/backdrop/blob/1.x/settings.php#L408 for details.

I was under the impression that [this line here](https://github.com/wappalyzer/wappalyzer/blob/master/src/technologies/b.json#L178) would make sure that this doesn't happen:
```json
    "excludes": "Drupal",
```

Can you please either fix or advise what needs to be done?

**Comment by nurbek91** [comment]
Hey @klonos , 
probably because of Drupal Multisite this error comes out. 
this should fix
```
"excludes": [
      "Drupal",
      "Drupal Multisite"
    ],
```
also add description, cpe, oss atrr

**Comment by klonos** [comment]
Thank you @nurbek91 and sorry for the delay in the reply.

I take it that "oss" is for "open source software", right? But what is "cpe"?

**Comment by klonos** [comment]
I've started a draft PR here: https://github.com/nurbek91/wappalyzer/pull/4

Soon as I understand what `cpe` is and what format I need to use for it, I'll update and finalize the PR for review.

**Comment by klonos** [comment]
...OK, read through https://cpe.mitre.org/specification and added a cpe entry accordingly. The PR is ready for review now.
