### ISSUE TITLE
 Suggestion to add support for CMS Craftum

### ISSUE THREAD

**Issue by Konstantin-craftum** [wappalyzer/wappalyzer#7674]
We would like to add our CMS - Craftum website builder: https://craftum.com/

So that when checking the site, with your plugin, it marks the sites collected on craftum.

Please clarify what information you need to provide from our team?

Waiting for your reply, thanks

**Comment by Konstantin-craftum** [comment]
> Привет@Konstantin-craftum, Спасибо!! думаю такой дорожки будет достаточно ![изображение](https://user-images.githubusercontent.com/3456008/243362672-5f47223c-06b3-4643-8dfe-ee4591b24121.png)


Hello, thanks! sent a request to add our CMS

**Comment by nurbek91** [comment]
@Konstantin-craftum  Hey mate, I have received your request. you misunderstood me.
This was an example of how a CMS can be defined. : )

`<meta name="generator" content="Craftum CMS 1.0.1">`
in your case the trace should look like somethig like  this
The version must be updated every time you update the CMS

**Comment by Konstantin-craftum** [comment]
> @Konstantin-craftum Hey mate, I have received your request. you misunderstood me. This was an example of how a CMS can be defined. : )
> 
> `<meta name="generator" content="Craftum CMS 1.0.1">` in your case the trace should look like this The version must be updated every time you update the CMS

Hi, thanks for the clarification.

If we just specify the meta tag:

<meta name="generator" content="Craftum CMS 1.0.1">

The version will be static, because the version of the product will not change with us.

Will this option suit you?

**Comment by nurbek91** [comment]
yes mate no problem. its can be without version

**Comment by Konstantin-craftum** [comment]
> yes mate no problem. its can be without version

Hello friend, we have changed the meta tag for our sites to:

<meta name="generator" content="Craftum CMS">

Is there anything else required of us?

**Comment by Konstantin-craftum** [comment]
@nurbek91 Hello! Can you tell me, please, what are the terms for adding our CMS? :)

**Comment by nurbek91** [comment]
added PR but in examples still wrong fingerprint 
You need to fix it urgently , because it spoils both your and our statistics :)
https://cheapsender.email/
https://lovi.link/

**Comment by nurbek91** [comment]
current fingerprint 
```
"meta": {
      "generator": "^Craftum CMS$"
    },
```
---->
<meta name="generator" content="Craftum CMS">

**Comment by Konstantin-craftum** [comment]
> added PR but in examples still wrong fingerprint You need to fix it urgently , because it spoils both your and our statistics :) https://cheapsender.email/ https://lovi.link/

Fixed, please check

**Comment by nurbek91** [comment]
Yes everything is fine now, thanks mate!!
