### ISSUE TITLE
Track Ruby if WEBrick is used

### ISSUE THREAD

**Issue by libDarkstreet** [wappalyzer/wappalyzer#7700]
Website: https://ruby-doc.org/stdlib-2.5.1/libdoc/webrick/rdoc/WEBrick.html
Detection: Server header containing the word `WEBrick`

A Webrick server header looks like this: `WEBrick/1.8.1 (Ruby/3.2.2/2023-03-30)` So this is also good for version detection.

**Comment by AliasIO** [comment]
Thanks!
