### ISSUE TITLE
The links in the README for wappalyzer-core no longer work

### ISSUE THREAD

**Issue by alexmorleyfinch** [wappalyzer/wappalyzer#7777]
**Describe the bug**
The README located [here](https://www.npmjs.com/package/wappalyzer-core) contains code that contains code comments that contain links that 404

**To Reproduce**
Open this link https://www.npmjs.com/package/wappalyzer-core
Read the code comments
Attempt to link to any of the links
See 404

**Expected behavior**
Don't link to 404s

**Comment by AliasIO** [comment]
Thanks, I'll update that. 👍
