### ISSUE TITLE
Track Kasada

### ISSUE THREAD

**Issue by sagunsh** [wappalyzer/wappalyzer#7857]
Vendor Site - https://www.kasada.io/
Category - Security
Example Sites:
https://www.crocs.com/
https://www.realestate.com.au/buy/list-1

Detections:
    Cookie - KP_UIDz
    JavaScript Object - KPSDK
    XHR - https://www.crocs.com/149e9513-01fa-4fb0-aad4-566afd725d1b/2d206a39-8ed7-437e-a3be-862e0f06eea3/ips.js

**Comment by AliasIO** [comment]
Thanks!
