### ISSUE TITLE
Docker image wappalyzer/cli does not work on Apple Silicon

### ISSUE THREAD

**Issue by praseodym** [wappalyzer/wappalyzer#7892]
**Platform**
Docker image `wappalyzer/cli`

**Describe the bug**
The Docker image `wappalyzer/cli` does not work on Apple Silicon.

**To Reproduce**

```
> docker run --rm -it wappalyzer/cli https://example.com
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{"urls":{"https://example.com/":{"status":0,"error":"Protocol error (Target.createTarget): Target closed."}},"technologies":[]}
```

**Expected behavior**
A linux/arm64 image is available that works on Apple Silicon platforms.

**Comment by AliasIO** [comment]
Try changing the first line in the [Dockerfile](https://github.com/wappalyzer/wappalyzer/blob/master/src/drivers/npm/Dockerfile) to this:

`FROM arm64v8/node:16-alpine3.16`

**Comment by praseodym** [comment]
Would it also be possible to provide an official image for arm64?
